force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 10th Nov 2020
Purpose: This field will store the dealer code for the department</description>
    <label>Department Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/SalesCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCompanyCode__c</fullName>
    <description>Sales Company Code</description>
    <label>Sales Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/DAOSSubmittedDate__c.field-meta.xml
<CustomField>
    <fullName>DAOSSubmittedDate__c</fullName>
    <label>Submitted Date (DAOS)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ExternalIdCXP__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdCXP__c</fullName>
    <description>ODS_CRP + ODS_DLR_CD + ODS_DLR_ORD_NO</description>
    <externalId>true</externalId>
    <label>External Id (CXP)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/OrderNoCXP__c.field-meta.xml
<CustomField>
    <fullName>OrderNoCXP__c</fullName>
    <description>생성규칙 (Order일자) + 주문헤더 갯수 (현재 최고값 + 1) (법인코드 + 딜러코드별)
  - YYYY(4)+MM(2)+DD(2)+SEQ(2)</description>
    <label>Order No (CXP)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ru_DAOSShippedQty__c.field-meta.xml
<CustomField>
    <fullName>ru_DAOSShippedQty__c</fullName>
    <label>Shipped Qty (DAOS)</label>
    <summarizedField>ProductRequestLineItem.DAOSShippedQty__c</summarizedField>
    <summaryForeignKey>ProductRequestLineItem.ParentId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ShipMode__c.field-meta.xml
<CustomField>
    <fullName>ShipMode__c</fullName>
    <label>Ship Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>G</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/TransmissionDate__c.field-meta.xml
<CustomField>
    <fullName>TransmissionDate__c</fullName>
    <label>Transmission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/ExternalIdCXP__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdCXP__c</fullName>
    <externalId>true</externalId>
    <label>External Id (CXP)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/ExternalIdDAOS__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdDAOS__c</fullName>
    <externalId>true</externalId>
    <label>External Id (DAOS)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/OrderedPartNo__c.field-meta.xml
<CustomField>
    <fullName>OrderedPartNo__c</fullName>
    <label>Ordered Part No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/OrderLineNoCXP__c.field-meta.xml
<CustomField>
    <fullName>OrderLineNoCXP__c</fullName>
    <label>Order Line No (CXP)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AS_SubmitPO_AmosRestAPI.cls
/******************************************************************************************
  * File Name   : AS_SubmitPO_AmosRestAPI
  * Created Date: 14th December 2020
  * Description : API required for GD-1391 ( Integration: submit purchase order ) and GD-1393 ( Integration: shipping information for purchase order ). It allows to send and recieive REST calls to/from AMOS system.
  * Author      : Konrad Maluszkiewicz
  * Modification Log
  * =======================================================================
  * Ver     Date             Author                      Modification
  * =======================================================================
  * 1.0     14.12.2020       Konrad Maluszkiewicz        Creation
  ****************************************************************************************/

@RestResource(urlMapping='/ProductRequestAPI/*')
global with sharing class AS_SubmitPO_AmosRestAPI {

    @HttpPut
    global static void upsertProductRequest() {
        String productRequestJSON = RestContext.request.requestBody.toString();
        System.debug('RestContext.request.requestBody = ' + productRequestJSON);

        ProductRequest prodRequest = jSON2ProductRequestWrapper(productRequestJSON);

        System.debug('prodRequest.ExternalIdCXP__c = ' + prodRequest.ExternalIdCXP__c);
        System.debug('prodRequest.ShipMode__c = ' + prodRequest.ShipMode__c);
        System.debug('prodRequest.Status = ' + prodRequest.Status);
        System.debug('prodRequest.ShipmentType = ' + prodRequest.ShipmentType);

        upsert prodRequest ExternalIdCXP__c;

// ProductRequest.ShipToAddress # ShipToAddress
// ProductRequest.ShipmentType # ShipmentType

        // tmp fields to include in wrapper (all fields of ProductRequest related to shipping):
        // ProductRequest.ExternalIdCXP__c # Text(255) (External ID) (Unique Case Insensitive) # __OK__
        // ProductRequest.ExternalIdDAOS__c # Text(255) (External ID) (Unique Case Insensitive)
        // ProductRequest.OrderNoCXP__c # Text(10)
        // ProductRequest.OrderType__c # Picklist
        // ProductRequest.ProductRequestNumber # Auto Number
        // ProductRequest.ru_DAOSShippedQty__c # Roll-Up Summary (SUM Product Request Line Item)
        // ProductRequest.Status # Picklist
        // ProductRequest.DAOSSubmittedDate__c # Date/Time
        // ProductRequest.TransmissionDate__c # Date/Time

        // List<Contact> contactsToUpdate = (List<Contact>) JSON.deserialize(RestContext.request.requestBody.toString(), List<Contact>.class);
        // System.debug('contactsToUpdate = ' + contactsToUpdate);
        // upsert contactsToUpdate DA_EGCID__c;
    }

    public static ProductRequest jSON2ProductRequestWrapper(String productRequestJSON) {
        return (ProductRequest)JSON.deserialize(productRequestJSON, ProductRequest.class);
    }

    public static ProductRequest getProductRequestForAMOSCallout(Id productRequestId) {
        ProductRequest prodRequest = [
            SELECT Id, CreatedDate, OrderNoCXP__c, OrderType__c, ShipMode__c, Description, Department__r.SalesCompanyCode__c, Department__r.Department_Code__c, (SELECT OrderLineNoCXP__c, OrderedPartNo__c, QuantityUnitOfMeasure FROM ProductRequestLineItems)
            FROM ProductRequest
            WHERE Id = :productRequestId
        ];

        // System.debug('prodRequest = ' + prodRequest);
        return prodRequest;
    }

    // @future(callout=true)
    public static HttpResponse sendProdReqToAMOS(Id productRequestId) {
        String authKey = 'Bearer Z2VuZXNpc2RpaDppbXNpITEyMzQ=';
        String reqBody = generateAmosProdReqCalloutBody(productRequestId);
        // String endpoint = 'http://exampleendpoint:7071/services/receive';
        String endpoint = 'http://10.115.192.157:7071/services/receive';

        Http mainHttp = new Http();
        HttpRequest httpReq = new HttpRequest();

        httpReq.setHeader('Authorization', authKey);
        httpReq.setHeader('Content-Type','application/json');
        httpReq.setHeader('ifId','IF_GME_CXP_DAOS_0001');
        httpReq.setHeader('ifSenderGp','EU');
        httpReq.setHeader('ifSender','CXP');
        httpReq.setHeader('ifReceiverGp','GME');
        httpReq.setHeader('ifReceiver','AMOS');
        httpReq.setHeader('ifTrackingId',String.valueOf(productRequestId));
        httpReq.setHeader('ifDateTime',System.now().format('yyyyMMddkkmmss'));
        httpReq.setBody(reqBody);
        httpReq.setMethod('PUT');
        httpReq.setEndpoint(endpoint);

        System.debug('httpReq = ' + httpReq);

        HttpResponse httpResp = mainHttp.send(httpReq);
        System.debug('httpReq.getHeader(\'ifId\') = ' + httpReq.getHeader('ifId'));
        System.debug('httpReq.getHeader(\'ifSenderGp\') = ' + httpReq.getHeader('ifSenderGp'));
        System.debug('httpReq.getHeader(\'ifSender\') = ' + httpReq.getHeader('ifSender'));
        System.debug('httpReq.getHeader(\'ifReceiverGp\') = ' + httpReq.getHeader('ifReceiverGp'));
        System.debug('httpReq.getHeader(\'ifReceiver\') = ' + httpReq.getHeader('ifReceiver'));
        System.debug('httpReq.getHeader(\'ifTrackingId\') = ' + httpReq.getHeader('ifTrackingId'));
        System.debug('httpReq.getHeader(\'ifDateTime\') = ' + httpReq.getHeader('ifDateTime'));
        return httpResp;
    }

    public static String generateAmosProdReqCalloutBody(Id productRequestId) {
        ProductRequest prodRequest = getProductRequestForAMOSCallout(productRequestId);
        JSONGenerator jSONMainGenerator = JSON.createGenerator(true);

        jSONMainGenerator.writeStartObject();

        if (prodRequest.Department__r == null) {
            jSONMainGenerator.writeStringField('SalesCompanyCode', '');
            jSONMainGenerator.writeStringField('DepartmentCode', '');
        } else {
            jSONMainGenerator.writeStringField('SalesCompanyCode', prodRequest.Department__r.SalesCompanyCode__c != null ? prodRequest.Department__r.SalesCompanyCode__c : '');
            jSONMainGenerator.writeStringField('DepartmentCode', prodRequest.Department__r.Department_Code__c != null ? prodRequest.Department__r.Department_Code__c : '');
        }

        jSONMainGenerator.writeStringField('OrderNoCXP', prodRequest.OrderNoCXP__c != null ? prodRequest.OrderNoCXP__c : '');
        jSONMainGenerator.writeStringField('OrderType', prodRequest.OrderType__c != null ? prodRequest.OrderType__c : '');
        jSONMainGenerator.writeStringField('OrderDate', prodRequest.CreatedDate.format('yyyyMMdd'));
        jSONMainGenerator.writeStringField('ShipMode', prodRequest.ShipMode__c != null ? prodRequest.ShipMode__c : '');
        jSONMainGenerator.writeStringField('Description', prodRequest.Description != null ? prodRequest.Description : '');
        jSONMainGenerator.writeStringField('CreationDate', prodRequest.CreatedDate.format('yyyyMMdd'));
        jSONMainGenerator.writeStringField('CreationTime', prodRequest.CreatedDate.format('kkmmss'));
        jSONMainGenerator.writeStringField('SendDate', System.now().format('yyyyMMdd'));
        jSONMainGenerator.writeStringField('SendTime', System.now().format('kkmmss'));

        jSONMainGenerator.writeFieldName('ProductRequestLineItems');
        jSONMainGenerator.writeStartArray();

        for (ProductRequestLineItem prodReqLineItem : prodRequest.ProductRequestLineItems) {
            jSONMainGenerator.writeStartObject();

            jSONMainGenerator.writeStringField('OrderLineNoCXP', prodReqLineItem.OrderLineNoCXP__c != null ? prodReqLineItem.OrderLineNoCXP__c : '');
            jSONMainGenerator.writeStringField('OrderedPartNo', (prodReqLineItem.OrderedPartNo__c != null ? prodReqLineItem.OrderedPartNo__c : ''));
            jSONMainGenerator.writeStringField('QuantityUnitOfMeasure', (prodReqLineItem.QuantityUnitOfMeasure != null ? prodReqLineItem.QuantityUnitOfMeasure : ''));

            jSONMainGenerator.writeEndObject();
        }

        jSONMainGenerator.writeEndArray();
        jSONMainGenerator.writeEndObject();

        System.debug('jSONMainGenerator.getAsString() = ' + jSONMainGenerator.getAsString());
        return jSONMainGenerator.getAsString();
    }
}