force-app/main/default/objects/Courtesy_Car_Contract__c/Courtesy_Car_Contract__c.object-meta.xml
<CustomObject>
    <description>GD-2328</description>
    <label>Courtesy Car Contract</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Courtesy Car Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courtesy Car Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/CustomerSignatureId__c.field-meta.xml
<CustomField>
    <fullName>CustomerSignatureId__c</fullName>
    <label>Pickup CustomerSignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Date_Time_PICK_UP__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_PICK_UP__c</fullName>
    <description>GD-2328
Timestamp of RecordType change (Delivery -&gt; Pic up)</description>
    <label>Date &amp; Time (PICK UP)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Delivery_CustomerSignatureId__c.field-meta.xml
<CustomField>
    <fullName>Delivery_CustomerSignatureId__c</fullName>
    <label>Delivery CustomerSignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Pickup_Signer_onbehalf__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Signer_onbehalf__c</fullName>
    <label>Pickup - Signer Name on behalf</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <description>GD-2328</description>
    <label>Service Booking</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Courtesy Car Contracts</relationshipLabel>
    <relationshipName>Courtesy_Car_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/SignatureId__c.field-meta.xml
<CustomField>
    <fullName>SignatureId__c</fullName>
    <label>Pickup DriverSignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/recordTypes/ReadOnly.recordType-meta.xml
<RecordType>
    <fullName>ReadOnly</fullName>
    <active>true</active>
    <label>ReadOnly</label>
</RecordType>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/SignatureId__c.field-meta.xml
<CustomField>
    <fullName>SignatureId__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>SignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/StatusConfirmation__c.object-meta.xml
<CustomObject>
    <description>Created By: Neha Aggrawal
Created Date: 06 Jan1020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1026</description>
    <label>Vehicle Condition Report</label>
    <nameField>
        <displayFormat>SC-{YYYY}{MM}-{0000}</displayFormat>
        <label>NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Condition Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusConfirmation__c/fields/Delivery_DriverSignatureId__c.field-meta.xml
<CustomField>
    <fullName>Delivery_DriverSignatureId__c</fullName>
    <label>Delivery DriverSignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/fields/Delivery_on_Behalf_SignatureId__c.field-meta.xml
<CustomField>
    <fullName>Delivery_on_Behalf_SignatureId__c</fullName>
    <label>Delivery on Behalf SignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/fields/Delivery_Signer_Name_on_behalf__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Signer_Name_on_behalf__c</fullName>
    <label>Delivery - Signer Name on behalf</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/fields/Pickup_On_Behalf_SignatureId__c.field-meta.xml
<CustomField>
    <fullName>Pickup_On_Behalf_SignatureId__c</fullName>
    <label>Pickup On Behalf SignatureId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Vehicle Condition Report</relationshipLabel>
    <relationshipName>Vehicle_Condition_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery</label>
</RecordType>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/Pickup.recordType-meta.xml
<RecordType>
    <fullName>Pickup</fullName>
    <active>true</active>
    <label>Pickup</label>
</RecordType>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/ReadOnly.recordType-meta.xml
<RecordType>
    <fullName>ReadOnly</fullName>
    <active>true</active>
    <label>ReadOnly</label>
</RecordType>

force-app/main/default/classes/AS_Signature.cls
/*
Author: Neha Aggrawal
Created Date: 15-01-2020
Story:https://jira.hyundai-autoever.eu/browse/GD-1026 
*Update Daniel Varhidi - add Courtesy_Car_Contract__c
*/

public without sharing class AS_Signature {
    
    public static Boolean isEmpty(Object o) {
        if (o == null) return true;
        
        if (o instanceOf String) {
            if (''.equals(o)) return true;
            if (''.equals(String.valueOf(o).trim())) return true; // SPACE도 empty로 본다.
        }
        
        return false;
    }
    @AuraEnabled
    public static String getRecordType(Map<String, Object> pmap) {
        Id recordId = (String) pmap.get('recordId');
        String recordtypename = '';
        String localName = recordId.getSobjectType().getDescribe().localName;
        System.debug('AS_Signature > getRecordType()');
        if ('StatusConfirmation__c'.equals(localName)) {
            Id RecordtypeId = [SELECT Id, RecordtypeId FROM StatusConfirmation__c where Id = :recordId].RecordtypeId;
            recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'StatusConfirmation__c'].Name;
        }else if ('Courtesy_Car_Contract__c'.equals(localName)) {
            Id RecordtypeId = [SELECT Id, RecordtypeId FROM Courtesy_Car_Contract__c where Id = :recordId].RecordtypeId;
            recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'Courtesy_Car_Contract__c'].Name;
        }
        return recordtypename;
    }
    @AuraEnabled
    public static Map<String, Object> doSaveSign(Map<String, Object> pmap, String selected, String recordTypeName, String signername) {
        System.debug(selected);
        Map<String, Object> returnMap = new Map<String, Object> ();
        ResponseStatus responseStatus = new ResponseStatus();
        
        //        try{
        // Param
        Id recordId = (String) pmap.get('recordId');
        String base64Data = (String) pmap.get('base64Data');
        
        if (AS_Signature.isEmpty(recordId)) {
            responseStatus.fail('Invalid Record ID');
            returnMap.put('responseStatus', responseStatus);
            return returnMap;
        }
        
        Datetime d = Datetime.now();
        String s = d.format('yyyy-MM-dd\' \'HH:mm:ss.SSS');
        //Save signature as attachment
        Attachment attach = new Attachment();
        attach.Body = EncodingUtil.base64Decode(base64Data);
        attach.Name = recordTypeName + '_' + selected + '_Sign_' + s + '.png';
        attach.IsPrivate = false;
        attach.ParentId = recordId;
        insert attach;
        //Update signature Id field as per record type and selected option by user
        String localName = recordId.getSobjectType().getDescribe().localName; //Object Name
        if (String.isNotBlank(localName)) {
            sObject obj = Schema.getGlobalDescribe().get(localName).newSObject(); //Object Instance
            if (obj != null && selected == 'Driver') {
                obj.put('Id', recordId);
                if (recordTypeName == 'Pickup')
                    obj.put('SignatureId__c', attach.Id);
                else
                    if (recordTypeName == 'Delivery')
                    obj.put('Delivery_DriverSignatureId__c', attach.Id);
                update obj;
            }
            else if (obj != null && selected == 'Customer') {
                obj.put('Id', recordId);
                if (recordTypeName == 'Pickup')
                    obj.put('CustomerSignatureId__c', attach.Id);
                else if (recordTypeName == 'Delivery')
                    obj.put('Delivery_CustomerSignatureId__c', attach.Id);
                update obj;
            }
            else if (obj != null && selected == 'Signer_On_Behalf') {
                obj.put('Id', recordId);
                if (recordTypeName == 'Pickup') {
                    obj.put('Pickup_Signer_onbehalf__c', signername);
                    obj.put('Pickup_On_Behalf_SignatureId__c', attach.Id);
                }
                if (recordTypeName == 'Delivery') {
                    obj.put('Delivery_Signer_Name_on_behalf__c', signername);
                    obj.put('Delivery_on_Behalf_SignatureId__c', attach.Id);
                }
                update obj;
            }
            //If pickup customer signature or signer signature and driver signature both not null, change record type to delivery   
            
            if ('StatusConfirmation__c'.equals(localName)) {
                StatusConfirmation__c parent = [SELECT Id, Repair__c, RecordtypeId, SignatureId__c, Delivery_on_Behalf_SignatureId__c, Pickup_On_Behalf_SignatureId__c, CustomerSignatureId__c, Delivery_CustomerSignatureId__c, Delivery_DriverSignatureId__c FROM StatusConfirmation__c WHERE Id = :recordId];
                /*
if (recordtypename == 'Pickup' && (parent.SignatureId__c != null && (parent.CustomerSignatureId__c != null || parent.Pickup_On_Behalf_SignatureId__c != null))) {
Id rtid = [Select Id, Name from RecordType where Name = 'Delivery' and SobjectType = 'StatusConfirmation__c'].Id;
parent.RecordtypeId = rtid;
update parent;
}
*/
                //If delivery customer signature or signer signature and driver signature both not null, change record type to readonly  
                if (recordtypename == 'Delivery' && (parent.Delivery_DriverSignatureId__c != null && (parent.Delivery_CustomerSignatureId__c != null || parent.Delivery_on_Behalf_SignatureId__c != null))) {
                    Id rtid = [Select Id, Name from RecordType where Name = 'ReadOnly' and SobjectType = 'StatusConfirmation__c'].Id;
                    parent.RecordtypeId = rtid;
                    update parent;
                    //Send Notification to Repair user
                    
                }
            }
            //If pickup customer signature or signer signature and driver signature both not null, change record type to pickup   
            if ('Courtesy_Car_Contract__c'.equals(localName)) {
                Courtesy_Car_Contract__c parent = [SELECT Id, Repair__c, RecordtypeId, SignatureId__c, Delivery_on_Behalf_SignatureId__c, Pickup_On_Behalf_SignatureId__c, CustomerSignatureId__c, Delivery_CustomerSignatureId__c, Delivery_DriverSignatureId__c FROM Courtesy_Car_Contract__c WHERE Id = :recordId];
                /*
//if (recordtypename == 'Delivery' && (parent.SignatureId__c != null && (parent.CustomerSignatureId__c != null || parent.Pickup_On_Behalf_SignatureId__c != null))) {
if (recordtypename == 'Delivery' &&  (parent.Delivery_DriverSignatureId__c != null && (parent.Delivery_CustomerSignatureId__c != null || parent.Delivery_on_Behalf_SignatureId__c != null))) {
Id rtid = [Select Id, Name from RecordType where Name = 'Pickup' and SobjectType = 'Courtesy_Car_Contract__c'].Id;
parent.RecordtypeId = rtid;
parent.Date_Time_PICK_UP__c = System.now();
update parent;
}
*/
                //If delivery customer signature or signer signature and driver signature both not null, change record type to readonly  
                if (recordtypename == 'Pickup' && (parent.SignatureId__c != null && (parent.CustomerSignatureId__c != null || parent.Pickup_On_Behalf_SignatureId__c != null))) {
                    Id rtid = [Select Id, Name from RecordType where Name = 'ReadOnly' and SobjectType = 'Courtesy_Car_Contract__c'].Id;
                    parent.RecordtypeId = rtid;
                    update parent;
                    //Send Notification to Repair user
                    
                }
            }
            
        } else {
            responseStatus.fail('Invalid Record ID');
            returnMap.put('responseStatus', responseStatus);
            return returnMap;
        }
        responseStatus.success();
        returnMap.put('responseStatus', responseStatus);
        returnMap.put('attachId', attach.Id);
        
        
        
        
        return returnMap;
    }
    
    public class ResponseStatus {
        @AuraEnabled public String result { get; set; }
        @AuraEnabled public String message { get; set; }
        
        public void success() {
            this.result = 'SUCCESS';
        }
        public void fail(String message) {
            this.result = 'fail';
            this.message = message;
        }
    }
}