force-app/main/default/objects/Courtesy_Car_Contract__c/Courtesy_Car_Contract__c.object-meta.xml
<CustomObject>
    <description>GD-2328</description>
    <label>Courtesy Car Contract</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Courtesy Car Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courtesy Car Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <description>GD-2328</description>
    <label>Service Booking</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Courtesy Car Contracts</relationshipLabel>
    <relationshipName>Courtesy_Car_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/recordTypes/ReadOnly.recordType-meta.xml
<RecordType>
    <fullName>ReadOnly</fullName>
    <active>true</active>
    <label>ReadOnly</label>
</RecordType>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairQuote__c/RepairQuote__c.object-meta.xml
<CustomObject>
    <description>Maintenance estimate information</description>
    <label>Repair Quote</label>
    <nameField>
        <displayFormat>RQ-{YYYY}{MM}-{0000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repair Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairQuote__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <description>created By:- Riddhi Mittal
Created at :- 11/11/2020
user story:- US- GD-1452
Purpose:- Need to create as per requirement</description>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Repair Quote</relationshipLabel>
    <relationshipName>Repair_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/StatusConfirmation__c.object-meta.xml
<CustomObject>
    <description>Created By: Neha Aggrawal
Created Date: 06 Jan1020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1026</description>
    <label>Vehicle Condition Report</label>
    <nameField>
        <displayFormat>SC-{YYYY}{MM}-{0000}</displayFormat>
        <label>NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Condition Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusConfirmation__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone &amp; Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Vehicle Condition Report</relationshipLabel>
    <relationshipName>Vehicle_Condition_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/Delivery.recordType-meta.xml
<RecordType>
    <fullName>Delivery</fullName>
    <active>true</active>
    <label>Delivery</label>
</RecordType>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/Pickup.recordType-meta.xml
<RecordType>
    <fullName>Pickup</fullName>
    <active>true</active>
    <label>Pickup</label>
</RecordType>

force-app/main/default/objects/StatusConfirmation__c/recordTypes/ReadOnly.recordType-meta.xml
<RecordType>
    <fullName>ReadOnly</fullName>
    <active>true</active>
    <label>ReadOnly</label>
</RecordType>

force-app/main/default/classes/AS_GeneratePDF.cls
/**
  Author: Neha Aggrawal
  Created Date: 18-01-2020
  Story:https://jira.hyundai-autoever.eu/browse/GD-1026
 */

public without sharing class AS_GeneratePDF {


	@AuraEnabled
	public static Map<String, Object> doInit(Map<String, Object> pmap) {
		Id recordId = (String) pmap.get('recordId');
		String recordtypename = '';
		String localName = recordId.getSobjectType().getDescribe().localName;
		if ('StatusConfirmation__c'.equals(localName)) {
			Id RecordtypeId = [SELECT Id, RecordtypeId FROM StatusConfirmation__c where Id = :recordId].RecordtypeId;
			recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'StatusConfirmation__c'].Name;
		} else if ('Courtesy_Car_Contract__c'.equals(localName)) {
			Id RecordtypeId = [SELECT Id, RecordtypeId FROM Courtesy_Car_Contract__c where Id = :recordId].RecordtypeId;
			recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'Courtesy_Car_Contract__c'].Name;
		}
		Map<String, Object> rmap = new Map<String, Object> ();


		// Custom Setting 이용.
		if ('StatusConfirmation__c'.equals(localName)) { // 상태확인서.
			rmap.put('initUrl', '/apex/AS_StatusConfirmationPDF?id=' + recordId + '&recordtypename=' + recordtypename);
		} /*else if ('Repair__c'.equals(localName)) { // 상세정비내역서
		   rmap.put('initUrl', '/apex/RepairDetailList?id=' + recordId);
		   } else if ('Invoice__c'.equals(localName)) { // 상세정비내역서
		   rmap.put('initUrl', '/apex/InvoicePDF?id=' + recordId);
		   } else if ('RepairQuote__c'.equals(localName)) { // 가견적서
		   rmap.put('initUrl', '/apex/RepairQuoteTempPDF?id=' + recordId);
		   } else if ('ServicePayment__c'.equals(localName)) {
		   rmap.put('initUrl', '/apex/PaymentReceiptPDF?id=' + recordId);
		   }*/ else if ('Courtesy_Car_Contract__c'.equals(localName)) {
			rmap.put('initUrl', '/apex/AS_CourtesyCarContractPDF?id=' + recordId + '&recordtypename=' + recordtypename);
		}

		return rmap;
	}

	@AuraEnabled
	public static Map<String, Object> doSavePDF(Map<String, Object> pmap) {
		System.debug('pmap :: ' + JSON.serialize(pmap));
		Id recordId = (String) pmap.get('recordId');
		String type = (String) pmap.get('type'); // delivery
		String recordtypename = '';
		String localName = recordId.getSobjectType().getDescribe().localName;
		// Custom Setting 이용.
		PageReference pdf = null;
		if ('StatusConfirmation__c'.equals(localName)) { // 상태확인서.
			Id RecordtypeId = [SELECT Id, RecordtypeId FROM StatusConfirmation__c where Id = :recordId].RecordtypeId;
			recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'StatusConfirmation__c'].Name;
			pdf = Page.AS_StatusConfirmationPDF;
         
		} else if ('Courtesy_Car_Contract__c'.equals(localName)) {
			Id RecordtypeId = [SELECT Id, RecordtypeId FROM Courtesy_Car_Contract__c where Id = :recordId].RecordtypeId;
			recordtypename = [Select Id, Name from RecordType where Id = :RecordtypeId and SobjectType = 'Courtesy_Car_Contract__c'].Name;
			pdf = Page.AS_CourtesyCarContractPDF;
		}

		pdf.getParameters().put('Id', recordId);
		//
		Blob body = Test.isRunningTest() ? Blob.valueOf('unit.Test') : pdf.getContentAsPDF();

		Datetime d = Datetime.now();
		//        String s = d.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
		String s = d.format('yyyy-MM-dd\' \'HH:mm:ss.SSS');

		if ('StatusConfirmation__c'.equals(localName)) {
			String label = StatusConfirmation__c.getSObjectType().getDescribe().getLabel(); // 상태확인서
			if (recordtypename == 'Pickup')
			s = recordtypename + '_' + label + '.' + s;
			else
			s = label + '.' + s;
		} else if ('Courtesy_Car_Contract__c'.equals(localName)) {
			String label = Courtesy_Car_Contract__c.getSObjectType().getDescribe().getLabel();
			if (recordtypename == 'Pickup')
			s = recordtypename + '_' + label + '.' + s;
			else
			s = label + '.' + s;
		}
		//Save generated PDF as file
		ContentVersion cv = new ContentVersion();

		cv.ContentLocation = 'S';
		cv.ContentDocumentId = null; //contentDocumentId;
		cv.VersionData = body; //EncodingUtil.base64Decode(base64Data);
		cv.Title = s + '.pdf';
		cv.PathOnClient = s + '.pdf';

		insert cv;

		ContentDocumentLink cdl = new ContentDocumentLink();

		cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;
		cdl.LinkedEntityId = recordId;
		cdl.ShareType = 'V';

		insert cdl;

		Map<String, Object> rmap = new Map<String, Object> ();

		rmap.put('ContentVersion', cv.Id);
		rmap.put('ContentDocumentLink', cdl.Id);
		//update completed
		if ('StatusConfirmation__c'.equals(localName)) {
			StatusConfirmation__c sc = new StatusConfirmation__c();
			if (recordtypename == 'ReadOnly') {
				sc.Id = recordId;
				sc.Completed__c = true;
				update sc;
			}
		}else if ('Courtesy_Car_Contract__c'.equals(localName)) {
			Courtesy_Car_Contract__c ccc = new Courtesy_Car_Contract__c();
			if (recordtypename == 'ReadOnly') {
				ccc.Id = recordId;
				ccc.Completed__c = true;
				update ccc;
			}
		}
		return rmap;
	}


}