force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: 
Purpose :- After Sales record of Customer.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStatus__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Confirmed By Hamid</description>
    <label>Representative</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AfterSales_SendCustomNotification.cls
/**
 * @author Daniel Varhidi
 * @date 18/01/2021
 * @description 
*/
global class AfterSales_SendCustomNotification {

	/**
	 * @description 
	 * @param title 
	 * @param body 
	 * @param notificationTypeId 
	 * @param targetId 
	 * @param recipientIdSet 
	 */
	public static void sendNotification(String title, String body, Id notificationTypeId, Id targetId, Set<String> recipientIdSet) {

		// Create a new custom notification
		Messaging.CustomNotification notification = new Messaging.CustomNotification();

		// Set the contents for the notification
		notification.setTitle(title);
		notification.setBody(body);

		// Set the notification type and target
		notification.setNotificationTypeId(notificationTypeId);
		notification.setTargetId(targetId);
		//Send 
		notification.send(recipientIdSet);
	}

	/**
	 * @description 
	 * @param title 
	 * @param body 
	 * @param notificationTypeDeveloperName 
	 * @param targetIdString 
	 * @param employeeIdString 
	 */
	@InvocableMethod(label = 'Send Custom Notification' description = 'Send Custom Notification' category = 'Custom Notification')
	public static void sendSampleNotificationFromProcessBuilder(List<FlowInputsSampleNotification> request) {
		String title;
		String body;
		String notificationTypeDeveloperName;
		String targetIdString;
		Employee__c emp;
		Id userId;

		for (FlowInputsSampleNotification input : request) {
			emp = AfterSales_SendCustomNotification.getEmployeeById(Id.valueOf(input.employeeIdString));
			if (emp != null) {
				userId = AfterSales_SendCustomNotification.getRecipientIdByEmployee(emp);
				if (userId != null) {
					if (emp.EmploymentStatus__c != 'On Leave') {
						if (emp.Country__c == 'Germany' || emp.Country__c == 'Switzerland') {
							title = input.titleGerman;
							body = input.bodyGerman;
						} else {
							title = input.titleEnglish;
							body = input.bodyEnglis;
						}
					} else {
						if (emp.Representative__r.Country__c == 'Germany' || emp.Representative__r.Country__c == 'Switzerland') {
							title = input.titleGerman;
							body = input.bodyGerman;
						} else {
							title = input.titleEnglish;
							body = input.bodyEnglis;
						}
					}

					notificationTypeDeveloperName = input.notificationTypeDeveloperName;
					targetIdString = input.targetIdString;
					Id notificationTypeId = getNotificationIdTypeByDeveloperName(notificationTypeDeveloperName);
					Set<String> recIdSet = new Set<String> ();
					recIdSet.add(userId);
					AfterSales_SendCustomNotification.sendNotification(title, body, notificationTypeId, Id.valueOf(targetIdString), recIdSet);
				}
			}
		}

	}

	/**
	 * @description input details that comes to apex from flow
	 */
	public class FlowInputsSampleNotification {

		@InvocableVariable
		public String titleEnglish;

		@InvocableVariable
		public String bodyEnglis;

		@InvocableVariable
		public String titleGerman;

		@InvocableVariable
		public String bodyGerman;

		@InvocableVariable
		public String notificationTypeDeveloperName;

		@InvocableVariable
		public String targetIdString;

		@InvocableVariable
		public String employeeIdString;

	}

	/**
	 * @description 
	 * @param devName 
	 * @return 
	 */
	public static Id getNotificationIdTypeByDeveloperName(String devName) {
		CustomNotificationType notificationType = [
		                                           SELECT Id, DeveloperName
		                                           FROM CustomNotificationType
		                                           WHERE DeveloperName = :devName
		                                          ];
		return notificationType.Id;
	}


	/**
	 * @description 
	 * @param u 
	 * @return 
	 */
	public static Id getRecipientIdByEmployee(Employee__c u) {
		System.debug('AfterSales_SendCustomNotification > getRecipientIdByEmployeeId > u: ' + u);
		if (u.EmploymentStatus__c == 'Inactive') {
			return null;
		} else if (u.EmploymentStatus__c == 'On Leave' && u.Representative__c != null && u.Representative__r.User__c != null) {
			return u.Representative__r.User__c;
		}

		return u.User__c;
	}

	/**
	 * @description 
	 * @param employeeId 
	 */
	public static Employee__c getEmployeeById(Id employeeId) {
		System.debug('AfterSales_SendCustomNotification > getEmployeeById > employeeId: ' + employeeId);
		List<Employee__c> empList = [
		                             SELECT Id, User__c, EmploymentStatus__c, Country__c,
		                             Representative__c, Representative__r.User__c, Representative__r.Country__c
		                             FROM Employee__c
		                             WHERE Id = :employeeId
		                            ];
		if (!empList.isEmpty()) {
			return empList.get(0);
		}
		return null;
	}


}