force-app/main/default/objects/Asset/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Describe Color of Vehicle.</description>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Latest_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Latest_Mileage__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 21/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <inlineHelpText>Latest Mileage</inlineHelpText>
    <label>Latest Mileage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Licence_plate_after_registration__c.field-meta.xml
<CustomField>
    <fullName>Licence_plate_after_registration__c</fullName>
    <label>Licence plate (after registration)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Model_year__c.field-meta.xml
<CustomField>
    <fullName>Model_year__c</fullName>
    <description>created By:- Abhishek Mamgain
Created at :- 09/12/2020
user story:- US- GD-1328
Purpose:- Need to create as per requirement</description>
    <label>Model year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Vehicle_Model_LTM__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model_LTM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 21/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Vehicle Model (LTM)</label>
    <referenceTo>VehicleModel__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 21/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>VIN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Service Bookings</relationshipLabel>
    <relationshipName>ServiceBookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inspection_Report__c/Vehicle_Inspection_Report__c.object-meta.xml
<CustomObject>
    <description>Created By: Nagendra Lagisetty
Created Date: 18 Jan 21
User Story: https://jira.hyundai-autoever.eu/browse/GD-2251</description>
    <label>Vehicle Inspection Report</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>VI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Inspection Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Inspection_Report__c/fields/Service_Booking__c.field-meta.xml
<CustomField>
    <fullName>Service_Booking__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Booking</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Vehicle Inspection Reports</relationshipLabel>
    <relationshipName>Vehicle_Inspection_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VehicleModel__c/VehicleModel__c.object-meta.xml
<CustomObject>
    <description>Vehicle type(Model) Management</description>
    <label>Vehicle Model</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/VehicleModel__c/fields/Engine_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Engine_Capacity__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <label>Engine Capacity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VehicleModel__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <label>Fuel Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VehicleModel__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VehicleModel__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <label>Model Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>G70</fullName>
    </customValue>
    <customValue>
        <fullName>G80</fullName>
    </customValue>
    <customValue>
        <fullName>G90</fullName>
    </customValue>
    <customValue>
        <fullName>GV80</fullName>
    </customValue>
    <description>Created By: Manoj Kumar
Created Date: 29/10/2020
User Story: GD-
Purpose :- After Sales record of Customer.</description>
    <masterLabel>Model</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <description>Vehicle Model Year

Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AS_VehicleInspectionExtension.cls
/*
Author: Neha Aggrawal
Created Date: 28-01-2020
Story:https://jira.hyundai-autoever.eu/browse/GD-1257
*/
public class AS_VehicleInspectionExtension {
 public list<VehicleInsWrapper> recordlist { get; set;}
    private final Vehicle_Inspection_Report__c vehicleInspection;
    public AS_VehicleInspectionExtension(ApexPages.StandardController stdController){
        this.vehicleInspection=(Vehicle_Inspection_Report__c)stdController.getRecord();
    }
    //wrapper class to get vehicle and vehicle model information
    public list<VehicleInsWrapper> getvehicleInsinfo(){
        recordlist = new List<VehicleInsWrapper>();
        Id  astId =[Select Service_Booking__r.Vehicle__c from Vehicle_Inspection_Report__c where Id =:vehicleInspection.Id].Service_Booking__r.Vehicle__c;
        for(Asset ast: [Select Id,Account.Name, Account.PersonMobilePhone, Account.PersonHomePhone, Account.PersonEmail, Vehicle_Model_LTM__r.Model__c,Vehicle_Model_LTM__r.Engine_Capacity__c,Model_Year__c,
                        Vehicle_Model_LTM__r.Fuel_Type__c,Color__c,
                         Latest_Mileage__c, Licence_plate_after_registration__c, VIN__c from Asset where Id =:astId] )
        {
            recordlist.add(new VehicleInsWrapper(ast));
        }
        System.debug(recordlist);
        return recordlist;
        
    }


public class VehicleInsWrapper {
public Asset record  { get; set;}
        public VehicleInsWrapper(Asset record){
            this.record = record;
           
        }
}
}