force-app/main/default/objects/Asset/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 29th Oct 2020
User Story: 
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 21/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 23rd Oct 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1238
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines Whether the department is active or closed</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Created By: Reza Sarwari, User Story: https://jira.hyundai-autoever.eu/browse/GD-1285</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Service_Package__c/Service_Package__c.object-meta.xml
<CustomObject>
    <description>According to Sales history Service Packages can be created by any department.

Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales record of Customer.</description>
    <label>Service Package</label>
    <nameField>
        <label>Service Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Packages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Package__c/fields/Auto_Link__c.field-meta.xml
<CustomField>
    <fullName>Auto_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By:- Riddhi Mittal
Created At:- 11/17/2020
US:- GD-1335
Purpose:- Initial connection Service Package/Vehicle automatic</description>
    <label>Auto Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/IsForAllModel__c.field-meta.xml
<CustomField>
    <fullName>IsForAllModel__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Is For All Model</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/SpLAST_MODIFIED_DATE__c.field-meta.xml
<CustomField>
    <fullName>SpLAST_MODIFIED_DATE__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>LAST MODIFIED DATE</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/SpValidity_From__c.field-meta.xml
<CustomField>
    <fullName>SpValidity_From__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Validity From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/SpValidity_Until__c.field-meta.xml
<CustomField>
    <fullName>SpValidity_Until__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Validity Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/Validity__c.field-meta.xml
<CustomField>
    <fullName>Validity__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Validity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Year</fullName>
            </value>
            <value>
                <fullName>2 Year</fullName>
            </value>
            <value>
                <fullName>3 Year</fullName>
            </value>
            <value>
                <fullName>4 Year</fullName>
            </value>
            <value>
                <fullName>5 Year</fullName>
            </value>
            <value>
                <fullName>6 Year</fullName>
            </value>
            <value>
                <fullName>7 Year</fullName>
            </value>
            <value>
                <fullName>8 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 06/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Package__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 06/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Vehicle Model</label>
    <referenceTo>VehicleModel__c</referenceTo>
    <relationshipLabel>Service Packages</relationshipLabel>
    <relationshipName>Service_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Package_Item__c/Service_Package_Item__c.object-meta.xml
<CustomObject>
    <description>Service package line items are details of service packages ,describe of every particular service. 

Created By: Manoj Kumar
Created Date: 05/11/2030
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Service Package Item</label>
    <nameField>
        <displayFormat>SPI - {0000}</displayFormat>
        <label>Service Package Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Package_Item__c/fields/Service_Package__c.field-meta.xml
<CustomField>
    <fullName>Service_Package__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 11/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Service Package</label>
    <referenceTo>Service_Package__c</referenceTo>
    <relationshipLabel>Service Package Items</relationshipLabel>
    <relationshipName>Service_package</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Package_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <defaultValue>16/100</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Tax</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle_Service_Package_Item__c/Vehicle_Service_Package_Item__c.object-meta.xml
<CustomObject>
    <description>Vehicle Service package line items are details of vehicle service packages, a clone of items in the service package. The records in this object are created by a flow: &apos;Create Vehicle Service Package Item&apos; when a vehicle Service Pacgake Record is created.

Created By: Neha Aggrawal
Created Date: 16/12/2020
User Story: Gd-1224
Purpose :- After Sales service available of Customer.</description>
    <label>Vehicle Service Package Item</label>
    <nameField>
        <label>Vehicle Service Package Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Service Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Service_Package_Item__c/fields/Service_Package_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Package_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by : Shashikant Bagale 
Created Date : 14/1/2020</description>
    <label>Service Package Item</label>
    <referenceTo>Service_Package_Item__c</referenceTo>
    <relationshipLabel>Vehicle Service Package Items</relationshipLabel>
    <relationshipName>Vehicle_Service_Package_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Service_Package_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <defaultValue>16/100</defaultValue>
    <label>Tax</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle_Service_Package_Item__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Vehicle Service Package Items</relationshipLabel>
    <relationshipName>Vehicle_Service_Package_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Service_Package_Item__c/fields/Vehicle_Service_Package__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Service_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Service Package</label>
    <referenceTo>VehicleServicePackage__c</referenceTo>
    <relationshipLabel>Vehicle Service Package Items</relationshipLabel>
    <relationshipName>Vehicle_Service_Package_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VehicleModel__c/VehicleModel__c.object-meta.xml
<CustomObject>
    <description>Vehicle type(Model) Management</description>
    <label>Vehicle Model</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/VehicleModel__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: Gd-1320
Purpose :- After Sales record of Customer.</description>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VehicleServicePackage__c/VehicleServicePackage__c.object-meta.xml
<CustomObject>
    <label>Vehicle Service Package</label>
    <nameField>
        <displayFormat>VSP-{0000}</displayFormat>
        <label>Vehicle Service Package</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Service Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VehicleServicePackage__c/fields/Service_Package__c.field-meta.xml
<CustomField>
    <fullName>Service_Package__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 13/11/2020
User Story: Gd-1223
Purpose :- After Sales service available of Customer.</description>
    <label>Service Package</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Service_Package__c.Vehicle_Model__c</field>
            <operation>equals</operation>
            <valueField>Service_Package__c.Vehicle__r.Vehicle_Model_LTM__c</valueField>
        </filterItems>
        <filterItems>
            <field>Service_Package__c.Vehicle_Model__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Package__c</referenceTo>
    <relationshipLabel>Vehicle Service Package</relationshipLabel>
    <relationshipName>Vehicle_Service_Package</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VehicleServicePackage__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 13/11/2020
User Story: Gd-1223
Purpose :- After Sales service available of Customer.</description>
    <label>Vehicle</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Vehicle Service Package</relationshipLabel>
    <relationshipName>Vehicle_Service_Package</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>G70</fullName>
    </customValue>
    <customValue>
        <fullName>G80</fullName>
    </customValue>
    <customValue>
        <fullName>G90</fullName>
    </customValue>
    <customValue>
        <fullName>GV80</fullName>
    </customValue>
    <description>Created By: Manoj Kumar
Created Date: 29/10/2020
User Story: GD-
Purpose :- After Sales record of Customer.</description>
    <masterLabel>Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AS_AssetTriggerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-17-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-17-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class AS_AssetTriggerTest {    
    @isTest 
    static void insertServicePackage() {
        // Riddhi is creating Service package record for US-1335
        Test.startTest();        
        Department__c dep = AfterSales_TestFactory.getDepartmentStore('Store','StoreCode', false);  
        GMECountry__c country = AfterSales_TestFactory.getCountry('Germany', 'DE', true);
        VehicleModel__c vM = new VehicleModel__c(
            Name = 'G70-Product Name',
            Model__c = 'G70'            
        );
        insert vM;
      
        Service_Package__c rec = new Service_Package__c();
        rec = TestDataSetFactory.createServicepackage('SP1', 
                                                      'Germany', 
                                                      system.today(),
                                                      system.today().addDays(3),
                                                      true,
                                                      '1 Year',
                                                      vM.Id );
        system.debug('rec is '+rec);
        Database.upsert  (rec,false);
        system.debug('SP1 record'+Database.upsert (rec,false));
        Service_Package__c SP2 = new Service_Package__c(
            Name = 'SP2',
            SpValidity_From__c = system.today(),
            SpValidity_Until__c = system.today().addDays(3),
            Country__c = 'Germany',
            Auto_Link__c = TRUE,
            IsActive__c = TRUE,
            SpLAST_MODIFIED_DATE__c = system.today(),
            Validity__c = '1 Year',
            Vehicle_Model__c = vM.Id
        );
        Database.upsert  (SP2,false);
        system.debug('SP2 record'+Database.upsert (SP2,false));
        
        Service_Package__c SP3 = new Service_Package__c(
            Name = 'SP3',
            SpValidity_From__c = system.today(),
            SpValidity_Until__c = system.today().addDays(3),
            Country__c = 'Germany',
            Auto_Link__c = TRUE,
            IsActive__c = TRUE,
            SpLAST_MODIFIED_DATE__c = system.today(),
            Validity__c = '1 Year',
            IsForAllModel__c = TRUE
        );
        Database.upsert  (SP3,false);
        Asset vehicle = TestDataSetFactory.createAssetWithVehicleModel('Test Vehicle', dep.Id , vM.Id);
        
        //Service_Package_Item__c record creation
        Service_Package_Item__c sPI = new Service_Package_Item__c(
        //Name = 'sPT1',
        Service_Package__c= SP3.id
        );
         Database.upsert  (sPI,false);
        
        //VehicleServicePackage__c recod creation
        VehicleServicePackage__c vSP = new VehicleServicePackage__c(
            Service_Package__c = SP3.id,
            Vehicle__c = vehicle.id
        );
        Database.upsert  (vSP,false);
        
        Vehicle_Service_Package_Item__c vSPI = new Vehicle_Service_Package_Item__c(
        Name = 'vSPI1',
            Vehicle__c = vehicle.id,
            Vehicle_Service_Package__c = vSP.id,
            tax__c= 16
            
        );
         Database.upsert  (vSPI,false);
        Vehicle_Service_Package_Item__c vSPI2 = new Vehicle_Service_Package_Item__c(
        Name = 'vSPI2',
            Vehicle__c = vehicle.id,
            Vehicle_Service_Package__c = vSP.id,
            tax__c= 16
            
        );
         Database.upsert  (vSPI2,false);
        Test.stopTest();
        
        
        string spcountry = 'Germany' ;
    string vehicleModelName  = 'xyzVM' ;
    Date DOR = system.today();
    boolean autolink = true;
    Date vFrom = system.today().addDays(-30);
    Date vuntile = system.today().addDays(30);
    string CheckValidity = '1 Year';
    Datetime checkdate = system.today();
    string spName  = 'xyz' ;
    string vName  = 'Trigger testclass' ;
    
VehicleModel__c vm1 = new VehicleModel__c(Name = vehicleModelName );
    insert vm1;
Service_Package__c sp  = new Service_Package__c(Name =spName, country__C=spcountry, Vehicle_Model__c =vm1.id,SpValidity_From__c= vFrom, SpValidity_Until__c = vuntile,Auto_Link__c = autolink, SpLAST_MODIFIED_DATE__c= checkdate ,Validity__c = CheckValidity  ); 
insert sp;
  Asset ass = new Asset (Name =vName,country__C=spcountry, Vehicle_Model_LTM__c =vm1.id,Date_of_Registration__c=DOR );
insert ass;
        
        
    }
    
}