force-app/main/default/objects/Asset/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 29th Oct 2020
User Story: 
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 23rd Oct 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1238
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 10th Nov 2020
Purpose: This field will store the dealer code for the department</description>
    <label>Department Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Major_Language__c.field-meta.xml
<CustomField>
    <fullName>Major_Language__c</fullName>
    <label>Language Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Contact_details__c.field-meta.xml
<CustomField>
    <fullName>Contact_details__c</fullName>
    <label>Contact Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: 
Purpose :- After Sales record of Customer.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmploymentEndDate__c.field-meta.xml
<CustomField>
    <fullName>EmploymentEndDate__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/21/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>Employment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmploymentStartDate__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStartDate__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/21/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>Employment Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Confirmed By Hamid</description>
    <label>Representative</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <inlineHelpText>Thies field value will be copied into the Account Team Member Role.
The Employee within the role &quot;Store Manager&quot; becomes Account Owner for all Accounts where his department is the PreferredFacility.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Adviser</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Insurance Manager</fullName>
            </value>
            <value>
                <fullName>Store Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Test Drive Manager</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Inventory Manager</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Receptionist</fullName>
            </value>
            <value>
                <fullName>Pick-up driver</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>GTA</fullName>
            </value>
            <value>
                <fullName>NSC Aftersales Manager</fullName>
            </value>
            <value>
                <fullName>Department Manager</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
                <isActive>false</isActive>
                <label>Butler</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <formula>TEXT(Department__r.Country__c)</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 22/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Repairs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repair__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Bookings</relationshipLabel>
    <relationshipName>Repair_Reservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Mayank Pant
Created Date: 30th Dec 2020
Purpose: This field will identify service resource belongs to which department</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceResource/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: Mayank Pant
Purpose: Each department will have one service territory</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Territories</relationshipLabel>
    <relationshipName>Service_Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 2nd Nov 2020
Purpose: Country of the Work Order</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AS_SchedRepair_AppointmentCreationTest.cls
/******************************************************************************************
  * File Name   : AS_SchedRepair_AppointmentCreationTest
  * Created Date: 21th December 2020
  * Description : Apex test class for AS_SchedRepair_AppointmentCreationCtrl. It's used for implementation of GD-547 ( Workshop scheduling for new repair reservation (GPA/SA) ). It's used for overwriting standard Service Booking (API Name: Repair__c) new record creation page.
  * Author      : Konrad Maluszkiewicz
  * Modification Log
  * =======================================================================
  * Ver     Date             Author                      Modification
  * =======================================================================
  * 1.0     21.12.2020       Konrad Maluszkiewicz        Creation
  ****************************************************************************************/

@isTest
private class AS_SchedRepair_AppointmentCreationTest {
/*
@AuraEnabled
public static String getRelatedDepartmentId() {
    Id currentUserId = UserInfo.getUserId();
    Id relatedDepartmentId;

    List<Employee__c> employeesList;
    try {
        employeesList = [
            SELECT Department__c
            FROM Employee__c
            WHERE User__c =:currentUserId
        ];
        System.debug('employeesList = ' + employeesList);

        if (employeesList?.size() == 1) {
            return employeesList[0].Department__c;
        }
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
    return '';
}
*/
    @testSetup
    static void setupTestData() {
        Asset assetRecord = new Asset(Name = 'Asset Name');
        insert assetRecord;

        // Department__c departmentRecord = new Department__c(Department_Code__c = 'test deparment code', Name = 'test department', State__c = 'Hessen');
        // insert departmentRecord;

        // Account accountRecord = new Account(Name = 'test Account', Major_Language__c = 'en_US', Preferred_ZipCode__c = 'test zip', Contact_Details__c = 'Email');
        // insert accountRecord;
        // Contact contactRecord = new Contact(AccountId = accountRecord.Id, LastName = 'Doe');
        // insert contactRecord;

        // //required fields missing: [EmploymentEndDate__c, EmploymentStartDate__c, Role__c, Salutation__c, Sex__c]
        // Employee__c employee = new Employee__c(User__c = UserInfo.getUserId(), Department__c = departmentRecord.Id, Contact__c = contactRecord.Id, Contact_details__c = 'Email', Country__c = 'United Kingdom', EmploymentEndDate__c = Date.today().addMonths(3), EmploymentStartDate__c = Date.today().addMonths(-3), Role__c = 'Technician', Salutation__c = 'Mr.', Sex__c = 'Male');
        // insert employee;


// OperatingHours operatingHoursRecord = new OperatingHours(
//     Name = '9 To 5',
//     TimeZone = 'Europe/Berlin'
// );
// insert operatingHoursRecord;

// ServiceTerritory serviceTerritoryRecord = new ServiceTerritory();
// serviceTerritoryRecord.Name = 'Test Territory';
// serviceTerritoryRecord.OperatingHoursId = operatingHoursRecord.Id;
// serviceTerritoryRecord.IsActive = TRUE;
// serviceTerritoryRecord.Department__c = departmentRecord.Id;
// insert serviceTerritoryRecord;

//         ServiceResource servResourceRecord = new ServiceResource(
//             AccountId = accountRecord.Id,
//             Department__c = departmentRecord.Id,
//             Employee__c = employee.Id,
//             Name = 'test service resource',
//             ResourceType = 'T',
//             RelatedRecordId = UserInfo.getUserId(),
//             IsActive = true
//         );
//         insert servResourceRecord;
// System.debug('inserted servResourceRecord = ' + servResourceRecord);

// ServiceTerritoryMember serviceTerritoryMemberRecord = new ServiceTerritoryMember();
// serviceTerritoryMemberRecord.TerritoryType = 'P';
// serviceTerritoryMemberRecord.ServiceTerritoryId = serviceTerritoryRecord.Id;
// serviceTerritoryMemberRecord.ServiceResourceId = servResourceRecord.Id;
// serviceTerritoryMemberRecord.EffectiveStartDate = Date.today().addYears(-1);
// serviceTerritoryMemberRecord.EffectiveEndDate = Date.today().addYears(2);
// insert serviceTerritoryMemberRecord;

//         Schema.Location locationRecord = new Schema.Location(
//             Name = 'test location',
//             LocationType = 'Warehouse'
//         );
//         insert locationRecord;

//         Schema.Address addressRecord = new Schema.Address(
//             ParentId = locationRecord.Id,
//             LocationType = 'Warehouse'
//         );
//         insert addressRecord;

// Case caseRecord = new Case(
//     AccountId = accountRecord.Id,
//     Status = 'New',
//     Origin = 'Homepage'
// );
// insert caseRecord;

// WorkOrder workOrderRecord = new WorkOrder(
//     AccountId = accountRecord.Id,
//     CaseId = caseRecord.Id
// );
// insert workOrderRecord;

//         ServiceAppointment servAppointmentRecord = new ServiceAppointment(
//             ParentRecordId = workOrderRecord.Id,
//             DueDate = System.now().addMonths(3),
//             Duration = 5,
//             SchedStartTime = System.now().addMonths(1),
//             SchedEndTime = System.now().addMonths(2),
//             EarliestStartTime = System.now().addDays(1)
//         );
//         insert servAppointmentRecord;

//         AssignedResource assignedResourceRecord = new AssignedResource(
//             ServiceAppointmentId = servAppointmentRecord.Id,
//             ServiceResourceId = servResourceRecord.Id
//         );
//         insert assignedResourceRecord;

// not to include START
        // SELECT Id, Employee__c
        // FROM ServiceResource
        // WHERE Employee__r.Department__c = :getRelatedDepartmentId()

        // Repair__c repairRecord = new Repair__c();
        // insert repairRecord;

        // ServiceAppointment sa = new ServiceAppointment();
        // sa.SchedStartTime = Date.today();
        // sa.SchedEndTime = Date.today();
        // insert sa;
// not to include END
    }

    // <c:AS_CustomLookup objectAPIName="Asset" IconName="standard:asset_object" selectedRecord="{!v.selectedLookUpAssetRecord}" label="Vehicle Name" id="assetCustomLookup"/>
/*

REQUIRED_FIELD_MISSING, Required fields are missing: [DepartmentVehicle__c, Service_Resource__c]: [DepartmentVehicle__c, Service_Resource__c]

*/
    @isTest
    static void testGetServiceBookingObjectLabel() {
        System.assertEquals(SObjectType.Repair__c.getLabel(), AS_SchedRepair_AppointmentCreationCtrl.getServiceBookingObjectLabel(), 'Service Booking (API Name: Repair__c) label isn\'t properly assigned...');
    }

    @isTest
    static void testCustomLookupControllerFetchingLookUpValues() {
        List<sObject> fetchedLookUpValues = AS_CustomLookUpController.fetchLookUpValues('Asset Name', 'Asset');
        System.assertEquals(1, fetchedLookUpValues.size());
    }

    @isTest
    static void testSetGeolocationsForAddresses() {
        Repair__c repair = new Repair__c();
        repair = AS_SchedRepair_AppointmentCreationCtrl.setGeolocationsForAddresses(repair,'','');
        System.assertEquals(45, repair.Pickup_Location_Geo__Latitude__s);
        System.assertEquals(90, repair.Pickup_Location_Geo__Longitude__s);
        System.assertEquals(50, repair.Drop_Off_Location_Geo__Latitude__s);
        System.assertEquals(95, repair.Drop_Off_Location_Geo__Longitude__s);
    }

    @isTest
    static void testGetRelatedDepartmentId() {
        Id departmentId = [
            SELECT Department__c
            FROM Employee__c
            WHERE User__c = :UserInfo.getUserId()
            LIMIT 1
        ][0].Department__c;

        System.assertEquals(departmentId, AS_SchedRepair_AppointmentCreationCtrl.getRelatedDepartmentId());
    }

    @isTest
    static void testGetRelatedDepartmentName() {
        System.assertEquals('test department', AS_SchedRepair_AppointmentCreationCtrl.getRelatedDepartmentName());
    }
/*
        let jSONRepairStr = '{"serviceBookingId":"' + assetRecord['Id']
        + '","customerId":"' + accountRecord['Id']
        + '","receivingDate":"' + component.find("receivingDate").get("v.value")
        + '","repairCompleteDate":"' + component.find("repairCompleteDate").get("v.value")
        + '","serviceResourceId":"' + serviceResourceRecord['Id']
        + '","pickupPersonId":"' + pickupPersonRecord['Id']
        + '","pickupAddressString":"' + component.find("pickupAddress").get("v.value")
        + '","dropOffAddress":"' + component.find("dropOffAddress").get("v.value")
        + '","repairPackagesList":' + JSON.stringify(repairPackagesList)
        + ',"individualRepairItemsList":' + JSON.stringify(individualRepairItemsList)
        + '}';
*/
    @isTest
    static void testInsertRepair() {
        Id assetId = [
            SELECT Id
            FROM Asset
        ].Id;

        Id accountId = [
            SELECT Id
            FROM Account
        ].Id;

        Id pickupPersonId = [
            SELECT Id
            FROM Employee__c
        ].Id;

        Id serviceResourceId = [
            SELECT Id
            FROM ServiceResource
        ].Id;

        String jSONRepair =
        '{"serviceBookingId":"' + assetId + 
        '","receivingDate":"' + String.valueOf(Date.today()) +
        '","repairCompleteDate":"' + String.valueOf(Date.today().addDays(3)) +
        '","serviceResourceId":"' + serviceResourceId +
        '","pickupAddressString":"test address 1' +
        '","dropOffAddress":"test address 2' +
        '","customerId":"' + accountId + 
        '","pickupPersonId":"' + pickupPersonId +
        '","repairPackagesList":[]' + 
        ',"individualRepairItemsList":[]}';

System.debug('flag_0 = ' + jSONRepair);

        AS_SchedRepair_AppointmentCreationCtrl.insertRepair(jSONRepair);

System.debug('flag_2 # repair = ' + [SELECT Name FROM Repair__c]);
        System.assertEquals(1, [SELECT Name FROM Repair__c].size());
    }

    @isTest
    static void testGetVehicleAndDepartmentWrapperJSON() {
        Id assetId = [
            SELECT Id
            FROM Asset
            WHERE Name = 'Asset Name'
        ].Id;
        Id departmentId = [
            SELECT Id
            FROM Department__c
            WHERE Name = 'test department'
        ].Id;
        String resultString = AS_SchedRepair_AppointmentCreationCtrl.getVehicleAndDepartmentWrapperJSON(String.valueOf(assetId));
        String expectedResult = '{"vehicle":{"attributes":{"type":"Asset","url":"/services/data/v50.0/sobjects/Asset/' + String.valueOf(assetId) + '"},"Id":"' + String.valueOf(assetId) + '","Name":"Asset Name"},"repairPackagesList":[],"departmentId":"' + String.valueOf(departmentId) + '"}';
        System.assertEquals(expectedResult, resultString);
    }

    // @isTest
    // static void testInsertRepair() {
        // String jSONRepair = '';
//         Id assetId = [SELECT Id FROM Asset LIMIT 1].Id;
// System.debug('assetId = ' + assetId);
//         Id accountId = [SELECT Id FROM Account LIMIT 1].Id;
// System.debug('accountId = ' + accountId);
//         Id employeeId = [SELECT Id FROM Employee__c LIMIT 1].Id;
// System.debug('employeeId = ' + employeeId);
        // String jSONRepair = '{"serviceBookingId":"' + assetId + '","customerId":"' + accountId + '","receivingDate":"' + Datetime.now().addMonths(-1).format('yyyy-MM-dd')
        // + '","repairCompleteDate":"' + Datetime.now().addMonths(1).format('yyyy-MM-dd') + '","serviceResourceId":"' + employeeId + '","pickupPersonId":"' + employeeId + '","pickupAddressString":"test 1","dropOffAddress":"test 2"}';

        // System.debug('jSONRepair = ' + jSONRepair);
        // String insertResult = AS_SchedRepair_AppointmentCreationCtrl.insertRepair(jSONRepair);
        // System.debug('insertResult = ' + insertResult);
        // System.assertEquals(18,insertResult.length());
    // }

    // @isTest
    // static void testMethod1() {
        // Asset assetRecord = new Asset();
        // assetRecord.Name = 'Test Asset Name';
        // insert assetRecord;

        // Employee__c employeeRecord = new Employee__c();
        // insert employeeRecord;

        // Repair__c repairRecord = new Repair__c();
        // repairRecord.DepartmentVehicle__c = assetRecord.Id;
        // REQUIRED_FIELD_MISSING, Required fields are missing: [Service_Resource__c]: [DepartmentVehicle__c, Service_Resource__c]
        // insert repairRecord;
        // System.assertEquals(1,[SELECT Id FROM ServiceAppointment].size());
    // }
}