force-app/main/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Bookings</relationshipLabel>
    <relationshipName>Repair_Reservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/StatusConfirmation__c.object-meta.xml
<CustomObject>
    <description>Created By: Neha Aggrawal
Created Date: 06 Jan1020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1026</description>
    <label>Vehicle Condition Report</label>
    <nameField>
        <displayFormat>SC-{YYYY}{MM}-{0000}</displayFormat>
        <label>NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Condition Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusConfirmation__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Vehicle Condition Report</relationshipLabel>
    <relationshipName>Vehicle_Condition_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inspection_Report__c/Vehicle_Inspection_Report__c.object-meta.xml
<CustomObject>
    <description>Created By: Nagendra Lagisetty
Created Date: 18 Jan 21
User Story: https://jira.hyundai-autoever.eu/browse/GD-2251</description>
    <label>Vehicle Inspection Report</label>
    <nameField>
        <displayFormat>VI-{0000}</displayFormat>
        <label>VI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Inspection Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AS_VehicleInspectionReportPDFtest.cls
/*
Author: Neha Aggrawal
Created Date: 28-01-2020
Story:https://jira.hyundai-autoever.eu/browse/GD-1257
*/
@IsTest
public with sharing class AS_VehicleInspectionReportPDFtest {

    @TestSetup
    static void setData() {
        Department__c dt= TestDataSetFactory.createDepartment('DT001','TestDepartment');
        Asset ast = TestDataSetFactory.createAsset('TestAsset',dt.Id);
        Repair__c rpr = TestDataSetFactory.createRepair(ast.Id);
        StatusConfirmation__c sc = TestDataSetFactory.createStatusConfirmation(rpr.Id);
       Vehicle_Inspection_Report__c vir = TestDataSetFactory.createVehicleInspectionReport(rpr.Id,sc.Id);
    }

    static testMethod void testCase01() {
        Test.startTest();
		Repair__c rpr = [SELECT Id FROM Repair__c];
        Vehicle_Inspection_Report__c vir=[Select Id from Vehicle_Inspection_Report__c];
        Map<String, Object> pmap = new Map<String, Object>();
        pmap.put('recordId', vir.Id);
        AS_VehicleInspectionReportPDF.doInit(pmap);
        AS_VehicleInspectionReportPDF.doSavePDF(pmap);
        
        ApexPages.StandardController stdcont = new ApexPages.StandardController(vir);
        AS_VehicleInspectionExtension testvir = new AS_VehicleInspectionExtension(stdcont);
        testvir.getvehicleInsinfo();
		PageReference pageRef = Page.AS_PDFVehicleInspectionReport;
        pageRef.getParameters().put('id', String.valueOf(vir.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

}