force-app/main/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/Courtesy_Car_Contract__c.object-meta.xml
<CustomObject>
    <description>GD-2328</description>
    <label>Courtesy Car Contract</label>
    <nameField>
        <displayFormat>CCC-{000000}</displayFormat>
        <label>Courtesy Car Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courtesy Car Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GD-2328</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courtesy Car Contracts</relationshipLabel>
    <relationshipName>Courtesy_Car_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Courtesy_Car_Contract__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <description>GD-2328</description>
    <label>Service Booking</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Courtesy Car Contracts</relationshipLabel>
    <relationshipName>Courtesy_Car_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Bookings</relationshipLabel>
    <relationshipName>Repair_Reservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StatusConfirmation__c/StatusConfirmation__c.object-meta.xml
<CustomObject>
    <description>Created By: Neha Aggrawal
Created Date: 06 Jan1020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1026</description>
    <label>Vehicle Condition Report</label>
    <nameField>
        <displayFormat>SC-{YYYY}{MM}-{0000}</displayFormat>
        <label>NO</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Condition Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusConfirmation__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Vehicle Condition Report</relationshipLabel>
    <relationshipName>Vehicle_Condition_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AS_GeneratePDF_test.cls
/*
 
  Author: Neha Aggrawal
  Created Date: 18-01-2020
  Story:https://jira.hyundai-autoever.eu/browse/GD-1026
 */

@IsTest
public with sharing class AS_GeneratePDF_test {

	@TestSetup
	static void setData() {
		Department__c dt = TestDataSetFactory.createDepartment('DT001', 'TestDepartment');
		Asset ast = TestDataSetFactory.createAsset('TestAsset', dt.Id);
		Repair__c rpr = TestDataSetFactory.createRepair(ast.Id);
		StatusConfirmation__c sc = TestDataSetFactory.createStatusConfirmation(rpr.Id);
		Courtesy_Car_Contract__c ccc = TestDataSetFactory.createCourtesyCarContract(rpr.Id);
	}

	static testMethod void testCase01() {
		Test.startTest();

		StatusConfirmation__c sc = [SELECT Id FROM StatusConfirmation__c];

		Map<String, Object> pmap = new Map<String, Object> ();
		pmap.put('recordId', sc.Id);
		//AS_GeneratePDF.doInit(pmap);
		ApexPages.StandardController stdcont = new ApexPages.StandardController(sc);
		AS_StatusConfirmationExtension testsc = new AS_StatusConfirmationExtension(stdcont);
		testsc.getvehicleinfo();
		testsc.SaveAttachment();
		PageReference pageRef = Page.AS_StatusConfirmationPDF;
		pageRef.getParameters().put('id', String.valueOf(sc.Id));
		Test.setCurrentPage(pageRef);
		// AS_GeneratePDF.doSavePDF(pmap);



		Test.stopTest();
	}

	static testMethod void testCourtesyCarContractExtension() {
		Test.startTest();

		Courtesy_Car_Contract__c ccc = [SELECT Id FROM Courtesy_Car_Contract__c];

		Map<String, Object> pmap = new Map<String, Object> ();
		pmap.put('recordId', ccc.Id);
		AS_GeneratePDF.doInit(pmap);
		ApexPages.StandardController stdcont = new ApexPages.StandardController(ccc);
		AS_CourtesyCarContractExtension testsc = new AS_CourtesyCarContractExtension(stdcont);

		PageReference pageRef = Page.AS_CourtesyCarContractPDF;
		pageRef.getParameters().put('id', String.valueOf(ccc.Id));
		Test.setCurrentPage(pageRef);
		//AS_GeneratePDF.doSavePDF(pmap);

		//('/lightning/r/Courtesy_Car_Contract__c/' + courtesyCarContract.Id + '/view')
		PageReference pageRef2 = testsc.SaveAttachment();
		System.debug('AS_GeneratePDF_test > testCourtesyCarContractExtension > pageRef2: ' + pageRef2);
		System.assertEquals('System.PageReference[/lightning/r/Courtesy_Car_Contract__c/' + ccc.Id + '/view]', String.valueOf(pageRef2), 'pageRef2');
		Test.stopTest();
	}

}