force-app/main/default/objects/Asset/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/Repair__c.object-meta.xml
<CustomObject>
    <description>Maintenance application information</description>
    <label>Service Booking</label>
    <nameField>
        <displayFormat>SB-{YYYY}{MM}-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 23/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Service Bookings</relationshipLabel>
    <relationshipName>Repair_Reservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repair_Quote_Line_Item__c/Repair_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <description>created By:- Riddhi Mittal
Created at :- 11/11/2020
user story:- US- GD-1452
Purpose:- Need to create as per requirement</description>
    <label>Repair Quote Line Item</label>
    <nameField>
        <label>Repair Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair_Quote_Line_Item__c/fields/Repair_Quote_Section__c.field-meta.xml
<CustomField>
    <fullName>Repair_Quote_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User Story: 1015
Created by: Neha Aggrawal</description>
    <label>Repair Quote Section</label>
    <referenceTo>Repair_Quote_Section__c</referenceTo>
    <relationshipLabel>Repair Quote Line Items</relationshipLabel>
    <relationshipName>Repair_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repair_Quote_Line_Item__c/fields/RepairQuote__c.field-meta.xml
<CustomField>
    <fullName>RepairQuote__c</fullName>
    <description>created By:- Riddhi Mittal
Created at :- 11/11/2020
user story:- US- GD-1452
Purpose:- Need to create as per requirement</description>
    <label>Repair Quote</label>
    <referenceTo>RepairQuote__c</referenceTo>
    <relationshipLabel>Repair Quote Line Items</relationshipLabel>
    <relationshipName>Repair_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repair_Quote_Section__c/Repair_Quote_Section__c.object-meta.xml
<CustomObject>
    <description>This object will hold Repair Quote Section information for a Service booking and repair quote.</description>
    <label>Repair Quote Section</label>
    <nameField>
        <label>Repair Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Quote Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repair_Quote_Section__c/fields/RepairQuote__c.field-meta.xml
<CustomField>
    <fullName>RepairQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LMS GD-1014 01/2/2020 
A section is dependent onm the quote</description>
    <label>Repair Quote</label>
    <referenceTo>RepairQuote__c</referenceTo>
    <relationshipLabel>Repair Quote Sections</relationshipLabel>
    <relationshipName>Repair_Quote_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RepairQuote__c/RepairQuote__c.object-meta.xml
<CustomObject>
    <description>Maintenance estimate information</description>
    <label>Repair Quote</label>
    <nameField>
        <displayFormat>RQ-{YYYY}{MM}-{0000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repair Quote</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairQuote__c/fields/Repair__c.field-meta.xml
<CustomField>
    <fullName>Repair__c</fullName>
    <description>created By:- Riddhi Mittal
Created at :- 11/11/2020
user story:- US- GD-1452
Purpose:- Need to create as per requirement</description>
    <label>Repair</label>
    <referenceTo>Repair__c</referenceTo>
    <relationshipLabel>Repair Quote</relationshipLabel>
    <relationshipName>Repair_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AS_TestRepairQuotePDF.cls
/*
 
Author: Neha Aggrawal
Created Date: 03-02-2020
Story:https://jira.hyundai-autoever.eu/browse/GD-1015
 */

@IsTest
public with sharing class AS_TestRepairQuotePDF {

    @TestSetup
    static void setData() {
        Department__c dt= TestDataSetFactory.createDepartment('DT001','TestDepartment');
        Asset ast = TestDataSetFactory.createAsset('TestAsset',dt.Id);
        Repair__c rpr = TestDataSetFactory.createRepair(ast.Id);
         RepairQuote__c rq = TestDataSetFactory.createRepairQuote(rpr.Id,ast.Id);
       Repair_Quote_Section__c rqs= TestDataSetFactory.createRepairQuoteSection(rq.Id,'Test Name');
        Repair_Quote_Section__c rqs1= TestDataSetFactory.createRepairQuoteSection(rq.Id,'Test Name1');
      Repair_Quote_Line_Item__c rqli=TestDataSetFactory.createRepairQuoteLineItem(rqs.Id,'Test Line Item');
        Repair_Quote_Line_Item__c rqli1=TestDataSetFactory.createRepairQuoteLineItem(rqs1.Id,'Test Line Item1');
        Repair_Quote_Line_Item__c rqli2=TestDataSetFactory.createRepairQuoteLineItem(rqs1.Id,'Test Line Item2');
    }

    static testMethod void testCase01() {
        Test.startTest();
		RepairQuote__c rq=[Select Id from RepairQuote__c limit 1];

        Map<String, Object> pmap = new Map<String, Object>();
        pmap.put('recordId', rq.Id);
		AS_RepairQuotePDF.doInit(pmap);
        ApexPages.StandardController stdcont = new ApexPages.StandardController(rq);
        AS_RepairQuotePDFExtension testrq = new AS_RepairQuotePDFExtension(stdcont);
        testrq.getvehicleinfo();
        testrq.getRepairQuoteSectioninfo();
        testrq.getrenderrepairQuoteLinemap();
        testrq.getrendersubtotoalmap();
         testrq.getGrandTotal();
        System.assertnotEquals(testrq.repairQuoteLineItemMap,null);
        System.assertnotEquals(testrq.SubtotalMap,null);
       
        
        PageReference pageRef = Page.AS_RepairQuotePDF;
        pageRef.getParameters().put('id', String.valueOf(rq.Id));
        Test.setCurrentPage(pageRef);
        AS_RepairQuotePDF.doSavePDF(pmap);
        
  		

        Test.stopTest();
    }

}