force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 27th Oct 2020
Purpose: This field will be used to determine the access of the product to users that belong to that country.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 27th Oct 2020
User Story:
Purpose:</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RepairPackage__c/RepairPackage__c.object-meta.xml
<CustomObject>
    <description>정비 패키지 마스터 정보 (Internal, Sales)</description>
    <label>Repair Package</label>
    <nameField>
        <label>Repair Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Package</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairPackage__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/9/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/RepairPackageItem__c.object-meta.xml
<CustomObject>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/2/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Repair Package Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Package Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairPackageItem__c/fields/fm_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>fm_ProductCode__c</fullName>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <inlineHelpText>Required if Line Item Type is Labor or Part</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Country__c</field>
            <operation>equals</operation>
            <valueField>$User.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Repair Package Item</relationshipLabel>
    <relationshipName>Repair_Package_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Quantity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/fields/RepairPackage__c.field-meta.xml
<CustomField>
    <fullName>RepairPackage__c</fullName>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Repair Package</label>
    <referenceTo>RepairPackage__c</referenceTo>
    <relationshipLabel>Repair Package Item</relationshipLabel>
    <relationshipName>RepairPackageItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AS_CloneRepairPackage_Handler.cls
/**
 * @author Daniel Varhidi
 * @Date 09/Febr/2021
 * @JIRA GD-2168
 * @description called from flow 'CloneRepairPackage 2' 
*/
public class AS_CloneRepairPackage_Handler {

	@InvocableMethod(label = 'cloneRepairPackageApexHandler' description = '' category = '')
	public static void cloneRepairPackageApexHandler(List<FlowInputs> request) {
		User currentUser = [
		                    SELECT Id, Country__c
		                    FROM User
		                    WHERE ID = :UserInfo.getUserId()
		                   ];
		List<RepairPackageItem__c> returnValueList = new List<RepairPackageItem__c> ();
		for (FlowInputs i : request) {
			List<RepairPackageItem__c> repairPackageItemList = i.repairPackageItemList;
			if (!repairPackageItemList.isEmpty()) {
				//Collect the Products
				Set<Id> productIdSet = new Set<Id> ();
				for (RepairPackageItem__c item : repairPackageItemList) {
					productIdSet.add(item.Product__c);
				}
				if (!productIdSet.isEmpty()) {
					List<Product2> prodList = [
					                           SELECT Id, ProductCode, Country__c
					                           FROM Product2
					                           WHERE Id IN :productIdSet AND Country__c = :currentUser.Country__c
					                          ];
					System.debug('AS_CloneRepairPackage_Handler > cloneRepairPackageApexHandler > prodList: ' + prodList);

					//create Map ProductCode-Product2
					Map<String, Product2> prodMapbyProductCode = new Map<String, Product2> ();
					for (Product2 pItem : prodList) {
						prodMapbyProductCode.put(pItem.ProductCode, pItem);
					}
					//clone the RepairPackage Items and modify the Unitprice
					for (RepairPackageItem__c item : repairPackageItemList) {
						//Check whether the necessary product is exist
						System.debug('AS_CloneRepairPackage_Handler > cloneRepairPackageApexHandler > item.fm_ProductCode__c: ' + item.fm_ProductCode__c);

						if (prodMapbyProductCode.containsKey(item.fm_ProductCode__c)) {
							RepairPackageItem__c newItem = new RepairPackageItem__c();
							newItem.Name = item.Name;
							newItem.Quantity__c = item.Quantity__c;
							newItem.RecordTypeId = item.RecordTypeId;
							newItem.RepairPackage__c = i.newrepairPackageId;
							newItem.Product__c = prodMapbyProductCode.get(item.fm_ProductCode__c).Id;

							returnValueList.add(newItem);
						}
					}
				}
			}
		}
		System.debug('AS_CloneRepairPackage_Handler > cloneRepairPackageApexHandler > returnValueList: ' + returnValueList);

		if (!returnValueList.isEmpty()) {
			insert returnValueList;
		}

	}

	/**
	 * @description input details that comes to apex from flow
	 */
	public class FlowInputs {

		@InvocableVariable
		public List<RepairPackageItem__c> repairPackageItemList;

		@InvocableVariable
		public String newrepairPackageId;

	}

}