force-app/main/default/objects/Product2/fields/LTS_Labor_Mast_ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>LTS_Labor_Mast_ExternalKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LTS Labor Mast ExternalKey</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSCarModelCode__c.field-meta.xml
<CustomField>
    <fullName>LTSCarModelCode__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSCarModelCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSCompanyKindCode__c.field-meta.xml
<CustomField>
    <fullName>LTSCompanyKindCode__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSCompanyKindCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSEnglishWorkName__c.field-meta.xml
<CustomField>
    <fullName>LTSEnglishWorkName__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSEnglishWorkName</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSFinalModifier__c.field-meta.xml
<CustomField>
    <fullName>LTSFinalModifier__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSFinalModifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSFirstRegistrant__c.field-meta.xml
<CustomField>
    <fullName>LTSFirstRegistrant__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSFirstRegistrant</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSFirstRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LTSFirstRegistrationDate__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSFirstRegistrationDate</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSIntegration__c.field-meta.xml
<CustomField>
    <fullName>LTSIntegration__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSIntegration</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSLaborNativeWorkName__c.field-meta.xml
<CustomField>
    <fullName>LTSLaborNativeWorkName__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSLaborNativeWorkName</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSLastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>LTSLastModifiedDate__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSLastModifiedDate</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSMainGroup__c.field-meta.xml
<CustomField>
    <fullName>LTSMainGroup__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSMainGroup</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSMessageID__c.field-meta.xml
<CustomField>
    <fullName>LTSMessageID__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSMessageID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSRelatedWorkDetails__c.field-meta.xml
<CustomField>
    <fullName>LTSRelatedWorkDetails__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSRelatedWorkDetails</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSRepairCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>LTSRepairCategoryCode__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSRepairCategoryCode</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSSPNCCode__c.field-meta.xml
<CustomField>
    <fullName>LTSSPNCCode__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSSPNCCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSSubGroup__c.field-meta.xml
<CustomField>
    <fullName>LTSSubGroup__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSSubGroup</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSTaskCodeEndTwoDigits__c.field-meta.xml
<CustomField>
    <fullName>LTSTaskCodeEndTwoDigits__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSTaskCodeEndTwoDigits</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSWhetherToDelete__c.field-meta.xml
<CustomField>
    <fullName>LTSWhetherToDelete__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSWhetherToDelete</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LTSWorkCode__c.field-meta.xml
<CustomField>
    <fullName>LTSWorkCode__c</fullName>
    <description>US- 1326  LTS integration interface
Created by:- Riddhi MIttal</description>
    <label>LTSWorkCode</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

force-app/main/default/classes/CXP_LTS_Labor_MastAPI.cls
/**
 * @author Daniel Varhidi
 * @createdDate 06/01/2021 
 * @JIRA GD-1326
 * @description 
*/
@RestResource(urlMapping = '/CXP_LTS_Labor_Mast/*')
global with sharing class CXP_LTS_Labor_MastAPI {

	@HttpPut
	global static void upsertLaborProduct() {

		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		List<Product2> recordsToUpsert = new List<Product2> ();
		Schema.SObjectField externalId = Product2.Fields.LTS_Labor_Mast_ExternalKey__c;
		Id laborRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Labor').getRecordTypeId();

		String jsonString = null;
		if (req.requestBody != null) {
			jsonString = req.requestBody.toString();
		}
		//System.debug('jsonString ============================> ' + jsonString);                            		                                              

		CXP_LTS_Labor_MastAPIWrapper wrapperList = (CXP_LTS_Labor_MastAPIWrapper) System.JSON.deserialize(jsonString, CXP_LTS_Labor_MastAPIWrapper.class);
		//System.debug('CXP_LTS_Labor_MastAPI > upsertLaborProduct > wrapperList.request.payload.T_DATA: ' + wrapperList.request.payload.T_DATA);        
		CXP_LTS_Labor_MastAPIWrapper.response responseInstance = new CXP_LTS_Labor_MastAPIWrapper.response(wrapperList.request.header.ifTrackingId);


		Set<String> ExternalKeySet = new Set<String> ();
		if (!wrapperList.request.payload.T_DATA.isEmpty()) {
			for (CXP_LTS_Labor_MastAPIWrapper.T_DATA wrapper : wrapperList.request.payload.T_DATA) {

				String ExternalKey;
				if (String.isNotBlank(wrapper.LTSWorkCode) || String.isNotBlank(wrapper.LTSEnglishWorkName)) {
					ExternalKey = wrapper.LTSWorkCode + wrapper.LTSEnglishWorkName;
				}
				//System.debug('External Id to check for Upsert ==============>' + ExternalKey);                

				if (ExternalKey == null) {
					responseInstance.response.payload.ResultCode = 'S';
					responseInstance.response.payload.ErrorMsg = ' ';
					responseInstance.response.payload.ErrorCode = ' ';
					String responseJSON = System.JSON.serialize(responseInstance, false);
					res.responsebody = blob.valueof(responseJSON);
				} else {
					Product2 prod = new Product2();
					prod.RecordTypeId = laborRecordTypeId;
					prod.LTS_Labor_Mast_ExternalKey__c = ExternalKey;
					ExternalKeySet.add(ExternalKey);
					if (String.isNotBlank(wrapper.LTSCompanyKindCode)) prod.LTSCompanyKindCode__c = wrapper.LTSCompanyKindCode;
					if (String.isNotBlank(wrapper.LTSCarModelCode)) prod.LTSCarModelCode__c = wrapper.LTSCarModelCode;
					if (String.isNotBlank(wrapper.LTSMainGroup)) prod.LTSMainGroup__c = wrapper.LTSMainGroup;
					if (String.isNotBlank(wrapper.LTSSubGroup)) prod.LTSSubGroup__c = wrapper.LTSSubGroup;
					if (String.isNotBlank(wrapper.LTSWorkCode)) prod.LTSWorkCode__c = wrapper.LTSWorkCode;
					if (String.isNotBlank(wrapper.LTSIntegration)) prod.LTSIntegration__c = wrapper.LTSIntegration;
					if (String.isNotBlank(wrapper.LTSKoreanWorkName)) prod.LTSLaborNativeWorkName__c = wrapper.LTSKoreanWorkName;
					if (String.isNotBlank(wrapper.LTSEnglishWorkName)) prod.LTSEnglishWorkName__c = wrapper.LTSEnglishWorkName;
					if (String.isNotBlank(wrapper.LTSSPNCCode)) prod.LTSSPNCCode__c = wrapper.LTSSPNCCode;
					if (String.isNotBlank(wrapper.LTSRepairCategoryCode)) prod.LTSRepairCategoryCode__c = wrapper.LTSRepairCategoryCode;
					if (String.isNotBlank(wrapper.LTSTaskCodeEndTwoDigits)) prod.LTSTaskCodeEndTwoDigits__c = wrapper.LTSTaskCodeEndTwoDigits;
					if (String.isNotBlank(wrapper.LTSMessageID)) prod.LTSMessageID__c = wrapper.LTSMessageID;
					if (String.isNotBlank(wrapper.LTSRelatedWorkDetails)) prod.LTSRelatedWorkDetails__c = wrapper.LTSRelatedWorkDetails;
					if (String.isNotBlank(wrapper.LTSWhetherToDelete)) prod.LTSWhetherToDelete__c = wrapper.LTSWhetherToDelete;
					if (String.isNotBlank(wrapper.LTSFinalModifier)) prod.LTSFinalModifier__c = wrapper.LTSFinalModifier;
					if (String.isNotBlank(wrapper.LTSLastModifiedDate)) prod.LTSLastModifiedDate__c = wrapper.LTSLastModifiedDate;
					if (String.isNotBlank(wrapper.LTSFirstRegistrant)) prod.LTSFirstRegistrant__c = wrapper.LTSFirstRegistrant;
					if (String.isNotBlank(wrapper.LTSFirstRegistrationDate)) prod.LTSFirstRegistrationDate__c = wrapper.LTSFirstRegistrationDate;
					recordsToUpsert.add(prod);
				}
			}
			//System.debug('Number of records in the list ' + recordsToUpsert.size());                        

			if (!recordsToUpsert.isEmpty()) {

				//Check the existing records
				List<Product2> existingProductList = [SELECT Id, Name, LTS_Labor_Mast_ExternalKey__c FROM Product2 WHERE LTS_Labor_Mast_ExternalKey__c IN :ExternalKeySet];
				//Create a Map from the List
				Map<String, Product2> existingProductMapByExternalKey = new Map<String, Product2> ();
				for (Product2 pItem : existingProductList) {
					existingProductMapByExternalKey.put(pItem.LTS_Labor_Mast_ExternalKey__c, pItem);
				}
				//Configure the new Product record
				for (Product2 pItem : recordsToUpsert) {
					if (!existingProductMapByExternalKey.containsKey(pItem.LTS_Labor_Mast_ExternalKey__c)) {
						pItem.Name = pItem.LTSEnglishWorkName__c;
						//Currency - Default value is EUR
					} 
				}

				try {
					//upsert recordsToUpsert LTS_Labor_Mast_ExternalKey__c;
					Database.upsert(recordsToUpsert, externalId, true);
					res.statusCode = 200;
					responseInstance.response.payload.ResultCode = 'S';
					responseInstance.response.payload.ErrorMsg = ' ';
					responseInstance.response.payload.ErrorCode = ' ';
					String responseJSON = System.JSON.serialize(responseInstance, false);
					res.responsebody = blob.valueof(responseJSON);
				}
				catch(Exception e) {
					System.debug('The following exception has occurred: ' + e.getMessage());
					res.statusCode = 400;
					responseInstance.response.payload.ResultCode = 'E';
					responseInstance.response.payload.ErrorMsg = e.getMessage();
					responseInstance.response.payload.ErrorCode = ' ';
					//responseInstance.payload.ErrorMsg = 'The payload contains duplicate values with the same external Id';
					String responseJSON = System.JSON.serialize(responseInstance, false);
					res.responsebody = blob.valueof(responseJSON);
				}
			}
		} else {
			responseInstance.response.payload.ResultCode = 'S';
			responseInstance.response.payload.ErrorMsg = ' ';
			responseInstance.response.payload.ErrorCode = ' ';
			String responseJSON = System.JSON.serialize(responseInstance, false);
			res.responsebody = blob.valueof(responseJSON);
		}
	}
}