force-app/main/default/objects/HereSettings__c/HereSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Here Settings</label>
</CustomObject>

force-app/main/default/objects/HereSettings__c/fields/TokenExpires__c.field-meta.xml
<CustomField>
    <fullName>TokenExpires__c</fullName>
    <label>Token Expires</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HereSettings__c/fields/TokenPart1__c.field-meta.xml
<CustomField>
    <fullName>TokenPart1__c</fullName>
    <label>Token Part1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HereSettings__c/fields/TokenPart2__c.field-meta.xml
<CustomField>
    <fullName>TokenPart2__c</fullName>
    <label>Token Part2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HereSettings__c/fields/TokenPart3__c.field-meta.xml
<CustomField>
    <fullName>TokenPart3__c</fullName>
    <label>Token Part3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HereSettings__c/fields/TokenPart4__c.field-meta.xml
<CustomField>
    <fullName>TokenPart4__c</fullName>
    <label>Token Part4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HereTokenIntegrationTest.cls
@IsTest
private class HereTokenIntegrationTest {
    
    @IsTest
    private static void hereTokenStoreTest() {

        HereSettings__c setting;
        //setting = new HereSettings__c(SetupOwnerId = UserInfo.getOrganizationId()); // [select Id from Organization].Id or UserInfo.getOrganizationId()
        //insert setting;

        Test.setMock(HttpCalloutMock.class, new HereCalloutMocksTest.HereTokenHttpCalloutMock());
        
        Test.startTest();
            HereTokenIntegration.storeHereToken();
        Test.stopTest();

        setting = HereSettings__c.getOrgDefaults();

        System.assert(setting != null, 'Custom setting should be there');
        System.assert(setting.SetupOwnerId == UserInfo.getOrganizationId(), 'Custom setting for Organization should be there');
        System.assert(String.isNotBlank(setting.TokenPart1__c), 'Custom setting TokenPart1__c should be there');
        System.assert(String.isNotBlank(setting.TokenPart2__c), 'Custom setting TokenPart2__c should be there');
        System.assert(String.isNotBlank(setting.TokenPart3__c), 'Custom setting TokenPart3__c should be there');
        System.assert(String.isNotBlank(setting.TokenPart4__c), 'Custom setting TokenPart4__c should be there');
        System.assert(setting.TokenExpires__c != null, 'Custom setting TokenExpires__c should be there');

    }

}