force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/BlockFlag__c.field-meta.xml
<CustomField>
    <fullName>BlockFlag__c</fullName>
    <label>Block Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/DealerCode__c.field-meta.xml
<CustomField>
    <fullName>DealerCode__c</fullName>
    <label>Dealer Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Department_Public_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Department_Public_Group_Id__c</fullName>
    <label>Department Public Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/SalesCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCompanyCode__c</fullName>
    <description>Sales Company Code</description>
    <label>Sales Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Created By: Reza Sarwari, User Story: https://jira.hyundai-autoever.eu/browse/GD-1285</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/BlockFlag__c.field-meta.xml
<CustomField>
    <fullName>BlockFlag__c</fullName>
    <label>Block flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/DealerCode__c.field-meta.xml
<CustomField>
    <fullName>DealerCode__c</fullName>
    <label>Dealer Code belonging to Sales person</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/fields/fm_Email__c.field-meta.xml
<CustomField>
    <fullName>fm_Email__c</fullName>
    <formula>User__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <label>Sales Person job position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Us- GD-1295 requirement</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <inlineHelpText>Thies field value will be copied into the Account Team Member Role.
The Employee within the role &quot;Store Manager&quot; becomes Account Owner for all Accounts where his department is the PreferredFacility.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Adviser</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Insurance Manager</fullName>
            </value>
            <value>
                <fullName>Store Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Test Drive Manager</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Inventory Manager</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Receptionist</fullName>
            </value>
            <value>
                <fullName>Pick-up driver</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>GTA</fullName>
            </value>
            <value>
                <fullName>NSC Aftersales Manager</fullName>
            </value>
            <value>
                <fullName>Department Manager</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
                <isActive>false</isActive>
                <label>Butler</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/SalesCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCompanyCode__c</fullName>
    <label>Sales company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/SalesPersonCode__c.field-meta.xml
<CustomField>
    <fullName>SalesPersonCode__c</fullName>
    <label>Sales Person Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GME_EmployeeTriggerHandler.cls
public class GME_EmployeeTriggerHandler implements GME_ITriggerHandler {

	public static Boolean TriggerDisabled = false;

	public Boolean IsDisabled()
	{
		if (GME_TriggerSettings__c.getOrgDefaults().EmployeeTriggerDisabled__c == true) {
			return true;
		}
		else {
			return TriggerDisabled;
		}
	}

	public void BeforeInsert(List<SObject> newItems) { }

	public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) { }

	public void BeforeDelete(Map<Id, SObject> oldItems) {
		if (!IsDisabled() && oldItems.size() == 1) {
			Employee__c e = (Employee__c) oldItems.values() [0];
			GME_EmployeeTriggerHandler.removeUserAccountTeamMembers(e.User__c);
		}
	}

	public void AfterInsert(Map<Id, SObject> newItems) {
		if (!IsDisabled() && newItems.size() == 1) {
			this.createAccountTeamMembers((Employee__c) newItems.values() [0], null);

			this.createUserSharing((Employee__c) newItems.values() [0]);
			addToPublicGroup(newItems.values());

			CXP_EmployeeCallout.sendRecordToDIH(newItems.keySet()); // Added as part of ERP interfaces making callouts to DIH
			System.debug('Future method called for the inserted Employee record');
		}
	}

	public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
		if (!IsDisabled() && newItems.size() == 1) {
			this.createAccountTeamMembers((Employee__c) newItems.values() [0], (Employee__c) oldItems.values() [0]);
			AfterSales_AssignGTAToAccount.assignOtherGTAToAccount((Map<Id, Employee__c>) newItems, (Map<Id, Employee__c>) oldItems); //GD-2170, GD-2173

			// Added as part of ERP interfaces making callouts to DIH			
			if (isRecordChanged((Employee__c) newItems.values() [0], (Employee__c) oldItems.values() [0])) {
				System.debug('Future method called for the updated Employee record');
				CXP_EmployeeCallout.sendRecordToDIH(newItems.keySet());				              
			}
			else {
				System.debug('Future method was not called because no values were changed in the Employee record');
			}

		}
	}

	public void AfterDelete(Map<Id, SObject> oldItems) {
		if (!IsDisabled() && oldItems.size() == 1) {
			this.removeAccountTeamMembers(((Employee__c) oldItems.values() [0]));
		}
	}

	public void AfterUndelete(Map<Id, SObject> oldItems) { }

	public void createUserSharing(Employee__c newEmployee) {
		try {
			List<Employee__c> Employees = new List<Employee__c> ([SELECT Id, User__c FROM Employee__c WHERE Department__c = :newEmployee.Department__c AND Role__c = 'Store Manager' limit 1]);

			Employee__c storeManager = Employees[0];

			UserShare us = new UserShare(UserAccessLevel = 'Read', UserOrGroupId = storeManager.User__c, UserId = newEmployee.User__c);
			insert us;


		} catch(Exception e) {
			System.debug('Exception: ' + e);
		}
	}

	public void createAccountTeamMembers(Employee__c newEmployee, Employee__c oldEmployee) {
		if (newEmployee.User__c != null && newEmployee.Department__c != null) {
			if (oldEmployee == null) {
				this.addAccountTeamMembers(newEmployee);
				GME_EmployeeTriggerHandler.createUserAccountTeamMembers(newEmployee.Department__c, newEmployee.User__c);
			}
			else if (oldEmployee.Department__c == null && newEmployee.Department__c != null) {
				GME_EmployeeTriggerHandler.createUserAccountTeamMembers(newEmployee.Department__c, newEmployee.User__c);
			}
			else if (oldEmployee.Department__c != newEmployee.Department__c) {
				GME_EmployeeTriggerHandler.createUserAccountTeamMembers(newEmployee.Department__c, newEmployee.User__c);
				this.removeAccountTeamMembers(oldEmployee);
				this.addAccountTeamMembers(newEmployee);
				List<UserAccountTeamMember> listUATM = new List<UserAccountTeamMember> ([SELECT Id FROM UserAccountTeamMember WHERE UserId = :oldEmployee.User__c OR OwnerId = :oldEmployee.User__c]);
				if (listUATM.size() > 0) {
					GME_EmployeeTriggerHandler.removeUserAccountTeamMembers(oldEmployee.User__c);
				}
			}
		}
	}

	@future
	public static void createUserAccountTeamMembers(Id departmentId, Id employeeUserId) {
		try {
			List<Employee__c> employees = new List<Employee__c> ([SELECT Department__c, User__c, Role__c FROM Employee__c WHERE Department__c = :departmentId AND User__c != :employeeUserId]);
			Employee__c currentEmployee = [SELECT Role__c FROM Employee__c WHERE Department__c = :departmentId AND User__c = :employeeUserId LIMIT 1];

			Flow.Interview.Create_User_AccountTeam_Member_2 myFlow =
			new Flow.Interview.Create_User_AccountTeam_Member_2(
			                                                    new map<String, Object> { 'Employee_Collection' => employees, 'UserId_CurrentUser' => employeeUserId, 'Role_CurrentUser' => currentEmployee.Role__c }
			);

			myFlow.start();
		} catch(Exception e) {
			System.debug('Exception: ' + e);
		}
	}

	@future
	public static void removeUserAccountTeamMembers(Id employeeUserId) {
		try {
			Flow.Interview.delete_UserAccountTeamMember myFlow =
			new Flow.Interview.delete_UserAccountTeamMember(
			                                                new map<String, Object> { 'UserId_CurrentUser' => employeeUserId }
			);

			myFlow.start();
		} catch(Exception e) {
			System.debug('Exception: ' + e);
		}
	}

	public void removeAccountTeamMembers(Employee__c oldEmployee) {
		try {
			delete[SELECT Id FROM AccountTeamMember WHERE Account.PreferredFacility__c = : oldEmployee.Department__c AND UserId = : oldEmployee.User__c];
		} catch(Exception e) {
			System.debug('Exception: ' + e);
		}
	}

	public void addAccountTeamMembers(Employee__c newEmployee) {
		System.debug('Adding new AccountTeamMembers...');
		List<AccountTeamMember> newTeams = new List<AccountTeamMember> ();

		for (Account acc :[SELECT Id FROM Account WHERE PreferredFacility__c = :newEmployee.Department__c]) {
			newTeams.add(
			             new AccountTeamMember(
			                                   AccountId = acc.Id,
			                                   UserId = newEmployee.User__c,
			                                   TeamMemberRole = newEmployee.Role__c,
			                                   AccountAccessLevel = 'Read',
			                                   OpportunityAccessLevel = 'None',
			                                   CaseAccessLevel = 'None',
			                                   ContactAccessLevel = 'Read'
			)
			);
		}

		insert newTeams;
		System.debug('Teams added: ' + newTeams);
	}

	public static void addToPublicGroup(List<Employee__c> newEmps) {
		Set<Id> empIds = new Set<Id> ();
		for (Employee__c emp : newEmps) {
			empIds.add(emp.Id);
		}
		addToPublicGroupFuture(empIds);
	}

	@future
	private static void addToPublicGroupFuture(Set<Id> empIds) {
		Set<Id> groupIds = new Set<Id> ();
		Set<Id> departmentIds = new Set<Id> ();
		List<GroupMember> listGroupMember = new List<GroupMember> ();
		List<Employee__c> newEmps = [SELECT Id, Department__c, User__c FROM Employee__c WHERE Id IN :empIds];

		for (Employee__c emp : newEmps) {
			departmentIds.add(emp.Department__c);
		}
		for (Department__c dep :[SELECT Id, Department_Public_Group_Id__c FROM Department__c WHERE Id IN :departmentIds]) {
			for (Employee__c emp : newEmps) {
				if (dep.Department_Public_Group_Id__c != null && dep.Id == emp.Department__c) {
					GroupMember gm = new GroupMember();
					gm.GroupId = dep.Department_Public_Group_Id__c;
					gm.UserOrGroupId = emp.User__c;
					listGroupMember.add(gm);
				}
			}
		}
		insert listGroupMember;
	}

	// Added as part of ERP interfaces making callouts to DIH
	public static Boolean isRecordChanged(Employee__c newRecord, Employee__c oldRecord) {
        
		if (newRecord.SalesCompanyCode__c != oldRecord.SalesCompanyCode__c || newRecord.SalesPersonCode__c != oldRecord.SalesPersonCode__c
		    || newRecord.name != oldRecord.name || newRecord.dealerCode__c != oldRecord.dealerCode__c
		    || newRecord.role__c != oldRecord.role__c || newRecord.department__c != oldRecord.department__c
		    || newRecord.jobPosition__c != oldRecord.jobPosition__c || newRecord.fm_Email__c != oldRecord.fm_Email__c
		    || newRecord.phone__c != oldRecord.phone__c || newRecord.blockFlag__c != oldRecord.blockFlag__c)
		return true;
		else
		return false;
	}

	
}