force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/recordTypes/GTA_Employee.recordType-meta.xml
<RecordType>
    <fullName>GTA_Employee</fullName>
    <active>true</active>
    <label>GTA Employee</label>
</RecordType>

force-app/main/default/objects/GTA__c/GTA__c.object-meta.xml
<CustomObject>
    <description>GD-2173, GD-2170</description>
    <label>GTA</label>
    <nameField>
        <displayFormat>GTA-{000000}</displayFormat>
        <label>GTA&apos;s Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GTAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GTA__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GTA__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The employee&apos;s role should be GTA.</errorMessage>
        <filterItems>
            <field>Employee__c.Role__c</field>
            <operation>equals</operation>
            <value>GTA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Mayank Pant
Created Date: 10th Nov 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1222
Purpose: This field is used to identify the department (Dealer) of the pricebook.</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AfterSales_SendCustomNotification_Test.cls
@isTest 
private class AfterSales_SendCustomNotification_Test {

	@isTest(seealldata = true)
	private static void testSendSampleNotificationFromProcessBuilder() {
		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);

		//Employee
		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployee(retailstoreDepartment.Id, testContactGTA1.Id, testUserGTA1.Id);

		//Input
		List<AfterSales_SendCustomNotification.FlowInputsSampleNotification> inputList = new List<AfterSales_SendCustomNotification.FlowInputsSampleNotification> ();
		AfterSales_SendCustomNotification.FlowInputsSampleNotification input = new AfterSales_SendCustomNotification.FlowInputsSampleNotification();
		input.titleEnglish = 'Title';
		input.bodyEnglis = 'Body';
		input.titleGerman = 'Title German';
		input.bodyGerman = 'Body German';
		input.targetIdString = String.valueOf(testAccount.Id);
		input.employeeIdString = String.valueOf(gtaEmployee1.Id);
		input.notificationTypeDeveloperName = 'sendAccountNotification';

		inputList.add(input);
		try {
			AfterSales_SendCustomNotification.sendSampleNotificationFromProcessBuilder(inputList);
		} catch(Exception ex) {
			System.assert(false);
		}
	}

	@isTest(seealldata = true)
	private static void testSendCustNotiHandlerGTAofDep() {
		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();
		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(retailstoreDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);
		GTA__c gta1 = new GTA__c(
		                         Department__c = retailstoreDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		insert gta1;

		//Pricebook
		Pricebook2 pb = TestDataSetFactory.createPriceBook('pb1','Service');

		//JobOrder
		WorkOrder wo = TestDataSetFactory.createJobOrderWithServiceCenter(testAccount.Id, pb.Id, retailstoreDepartment.Id);

		//JobOrder Extension
		Job_Order_Extension__c joe = TestDataSetFactory.createJobOrderExtension(wo.Id, 'joeName');

		//Input
		List<AfterSales_SendCustNotiHandler_GTAofDep.FlowInputs> inputList = new List<AfterSales_SendCustNotiHandler_GTAofDep.FlowInputs> ();
		AfterSales_SendCustNotiHandler_GTAofDep.FlowInputs input = new AfterSales_SendCustNotiHandler_GTAofDep.FlowInputs();
		input.titleEnglish = 'Title';
		input.bodyEnglis = 'Body';
		input.titleGerman = 'Title German';
		input.bodyGerman = 'Body German';
		input.targetIdString = String.valueOf(joe.Id);
		input.servicecenterIdString = String.valueOf(retailstoreDepartment.Id);
		input.notificationTypeDeveloperName = 'sendAccountNotification';

		inputList.add(input);
		try {
			AfterSales_SendCustNotiHandler_GTAofDep.sendNotificationFromProcessBuilderToGTAofDepartment(inputList);
		} catch(Exception ex) {
			System.assert(false);
		}
	}
}