force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 23rd Oct 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1238
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: 
Purpose :- After Sales record of Customer.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 22nd Oct 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Mayank Pant
Created Date: 10th Nov 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1222
Purpose: This field is used to identify the department (Dealer) of the pricebook.</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Pricebook2.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 27th Oct 2020
Purpose: This field will be used to determine the access of the product to users that belong to that country.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 27th Oct 2020
User Story:
Purpose:</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <label>Part</label>
       
</RecordType>

force-app/main/default/objects/RepairPackage__c/RepairPackage__c.object-meta.xml
<CustomObject>
    <description>정비 패키지 마스터 정보 (Internal, Sales)</description>
    <label>Repair Package</label>
    <nameField>
        <label>Repair Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Package</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairPackage__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/9/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RepairPackage__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/2/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Service Center</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Repair Package</relationshipLabel>
    <relationshipName>RepairPackage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RepairPackage__c/recordTypes/NSC.recordType-meta.xml
<RecordType>
    <fullName>NSC</fullName>
    <active>true</active>
    <label>NSC</label>
</RecordType>

force-app/main/default/objects/RepairPackageItem__c/RepairPackageItem__c.object-meta.xml
<CustomObject>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/2/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Repair Package Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repair Package Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RepairPackageItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <inlineHelpText>Required if Line Item Type is Labor or Part</inlineHelpText>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Country__c</field>
            <operation>equals</operation>
            <valueField>$User.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Repair Package Item</relationshipLabel>
    <relationshipName>Repair_Package_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Quantity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/fields/RepairPackage__c.field-meta.xml
<CustomField>
    <fullName>RepairPackage__c</fullName>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-1228
Purpose: Basic level object</description>
    <label>Repair Package</label>
    <referenceTo>RepairPackage__c</referenceTo>
    <relationshipLabel>Repair Package Item</relationshipLabel>
    <relationshipName>RepairPackageItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RepairPackageItem__c/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <label>Part</label>
</RecordType>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AS_CloneRepairPackage_HandlerTest.cls
/**
 * @author Daniel Varhidi
 * @description 
 * @created 21/01/2021
 * @JIRA GD-2168
*/
@isTest
private class AS_CloneRepairPackage_HandlerTest {

	@isTest
	private static void testName() {
		//User
		User testUser = TestDataSetFactory.createSampleUser();
		testUser.Country__c = 'Germany';
		update testUser;
		//Department
		Department__c dep = TestDataSetFactory.createDepartment('111', 'depName'); //String code, String name
		//Account
		Account acc = TestDataSetFactory.createSampleAccount(dep.Id); //Id prefferedFacilityId
		//Contact
		Contact con = TestDataSetFactory.createSampleContact2(acc.Id);//Id accountId
		//Employee
		Employee__c emp = TestDataSetFactory.createEmployee(dep.Id,con.Id, UserInfo.getUserId());//Id prefferedFacilityId, Id contactId, Id userId
		//Product
		Product2 p = TestDataSetFactory.createProduct('valami', true, 'Germany'); //String name, Boolean isActiveBoolean, String country
		// NSC PriceBook for Germany
		Pricebook2 pb = TestDataSetFactory.createNSCPriceBook('ValamiPb', 'Service', 'Germany'); //String name, String type, String country
		//Standard PBEntry
		Id stdPbeId = Test.getStandardPricebookId();
		PricebookEntry standardpbe1 = TestDataSetFactory.createPriceBookEntry(10, stdPbeId, p.Id);
		//PriceBookEntry
		PricebookEntry pbe = TestDataSetFactory.createPriceBookEntry(10, pb.Id, p.Id); //Integer unitprice, Id pricebookId, Id ProductId
		List<PricebookEntry> pbeList = new List<PricebookEntry> ();
		pbeList.add(pbe);
		//Repair Package
		RepairPackage__c rp = TestDataSetFactory.createRepairPackage();
		RepairPackage__c rp2 = TestDataSetFactory.createRepairPackage();
		//Repair Package Item
		RepairPackageItem__c rpi = new RepairPackageItem__c(
		                                                    Name = 'rpi Name',
		                                                    RecordTypeId = RepairPackageItem__c.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Part').getRecordTypeId(),
		                                                    RepairPackage__c = rp.Id,
		                                                    Product__c = p.Id,
		                                                    Quantity__c = 2
		);
		List<RepairPackageItem__c> rpiList = new List<RepairPackageItem__c>();
		rpiList.add(rpi);

		System.runAs(testUser){
		List<AS_CloneRepairPackage_Handler.FlowInputs> flowInputList = new List<AS_CloneRepairPackage_Handler.FlowInputs> ();
		AS_CloneRepairPackage_Handler.FlowInputs flinput = new AS_CloneRepairPackage_Handler.FlowInputs();
		flinput.newrepairPackageId = rp2.Id;
		//flinput.priceBookEntryList = pbeList;
		flinput.repairPackageItemList = rpiList;
		flowInputList.add(flinput);

		AS_CloneRepairPackage_Handler.cloneRepairPackageApexHandler(flowInputList);

		List<RepairPackageItem__c> newrpiList = [SELECT Id FROM RepairPackageItem__c WHERE RepairPackage__c = :rp2.Id];
		System.assertEquals(rpiList.size(), newrpiList.size(), 'Number of new Repair Package Items');
		}
	}
}