force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Mayank Pant
Created Date: 23rd Oct 2020
User Story: https://jira.hyundai-autoever.eu/browse/GD-1238
Purpose:</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/fields/Major_Language__c.field-meta.xml
<CustomField>
    <fullName>Major_Language__c</fullName>
    <label>Language Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/NSC_Aftersales_Manager__c.field-meta.xml
<CustomField>
    <fullName>NSC_Aftersales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSC Aftersales Manager</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Employee role has to be NSC Aftersales Manager and employee&#39;s country has to equal to country of department.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>Employee__c.Country__c</valueField>
        </filterItems>
        <filterItems>
            <field>Employee__c.Role__c</field>
            <operation>equals</operation>
            <value>NSC Aftersales Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Departments (Add NSC Aftersales Manager)</relationshipLabel>
    <relationshipName>Departments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/recordTypes/Service_Center.recordType-meta.xml
<RecordType>
    <fullName>Service_Center</fullName>
    <active>true</active>
    <label>Service Center</label>
</RecordType>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Contact_details__c.field-meta.xml
<CustomField>
    <fullName>Contact_details__c</fullName>
    <label>Contact Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>$User.Country</defaultValue>
    <description>Created By: Manoj Kumar
Created Date: 02/11/2030
User Story: 
Purpose :- After Sales record of Customer.</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EmploymentStatus__c.field-meta.xml
<CustomField>
    <fullName>EmploymentStatus__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Confirmed By Hamid</description>
    <label>Representative</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/recordTypes/GTA_Employee.recordType-meta.xml
<RecordType>
    <fullName>GTA_Employee</fullName>
    <active>true</active>
    <label>GTA Employee</label>
</RecordType>

force-app/main/default/objects/GTA__c/GTA__c.object-meta.xml
<CustomObject>
    <description>GD-2173, GD-2170</description>
    <label>GTA</label>
    <nameField>
        <displayFormat>GTA-{000000}</displayFormat>
        <label>GTA&apos;s Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GTAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GTA__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GTA__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The employee&apos;s role should be GTA.</errorMessage>
        <filterItems>
            <field>Employee__c.Role__c</field>
            <operation>equals</operation>
            <value>GTA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created By: Mayank Pant 
Created Date: 21st Oct 2020
Purpose: This picklist will be used across different objects.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AfterSales_AssignGTAToAccountTest.cls
@isTest
private class AfterSales_AssignGTAToAccountTest {

	@isTest
	private static void createPersonAccount1GTA() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUser();
		//User testUserGTA2 = TestDataSetFactory.createSampleUser();
		//User testUserNSCAfterSalesManager = TestDataSetFactory.createSampleUser();

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContact = new Contact(
		                                  AccountId = testAccount.Id,
		                                  LastName = 'TestContact',
		                                  FirstName = 'firstname',
		                                  MailingCountry = 'Germany',
		                                  MailingStreet = 'Sonnenstraße 71',
		                                  MailingPostalCode = '80331',
		                                  MailingCity = 'Stuttgart',
		                                  Job_Title__c = 'Employee',
		                                  Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();
		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContact.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);

		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, PersonMailingLatitude, PersonMailingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee1.Id, acc1.Assigned_GTA__c, 'Assigned GTA');

	}

	@isTest
	private static void createAccount0GTA() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserNSCAfterSalesManager = TestDataSetFactory.createSampleUserUniqueUserName('un3@mytestdomain.developer', 'nck3');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact

		Contact testContactManager1 = new Contact(
		                                          AccountId = testAccount.Id,
		                                          LastName = 'TestContact3',
		                                          FirstName = 'firstname3',
		                                          MailingCountry = 'Germany',
		                                          MailingStreet = 'Sonnenstraße 60',
		                                          MailingPostalCode = '80334',
		                                          MailingCity = 'Stuttgart',
		                                          Job_Title__c = 'Employee',
		                                          Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c managerEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactManager1.Id, testUserNSCAfterSalesManager.Id, 'NSC Aftersales Manager', gtaEmployeeRecordTypeId);

		serviceCenterDepartment.NSC_Aftersales_Manager__c = managerEmployee2.Id;
		update serviceCenterDepartment;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(null, acc1.Assigned_GTA__c, 'Assigned GTA');

	}

	@isTest
	private static void createAccount2GTA() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		User testUserGTA2 = TestDataSetFactory.createSampleUserUniqueUserName('un2@mytestdomain.developer', 'nck2');
		User testUserNSCAfterSalesManager = TestDataSetFactory.createSampleUserUniqueUserName('un3@mytestdomain.developer', 'nck3');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactGTA2 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact2',
		                                      FirstName = 'firstname2',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 71',
		                                      MailingPostalCode = '80331',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactManager1 = new Contact(
		                                          AccountId = testAccount.Id,
		                                          LastName = 'TestContact3',
		                                          FirstName = 'firstname3',
		                                          MailingCountry = 'Germany',
		                                          MailingStreet = 'Sonnenstraße 60',
		                                          MailingPostalCode = '80334',
		                                          MailingCity = 'Stuttgart',
		                                          Job_Title__c = 'Employee',
		                                          Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c gtaEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA2.Id, testUserGTA2.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c managerEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactManager1.Id, testUserNSCAfterSalesManager.Id, 'NSC Aftersales Manager', gtaEmployeeRecordTypeId);

		serviceCenterDepartment.NSC_Aftersales_Manager__c = managerEmployee2.Id;
		update serviceCenterDepartment;

		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		GTA__c gta2 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee2.Id
		);
		gtaLIst.add(gta2);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(null, acc1.Assigned_GTA__c, 'Assigned GTA');

	}

	@isTest
	private static void createAccount2GTA2Manager() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		User testUserGTA2 = TestDataSetFactory.createSampleUserUniqueUserName('un2@mytestdomain.developer', 'nck2');
		User testUserNSCAfterSalesManager = TestDataSetFactory.createSampleUserUniqueUserName('un3@mytestdomain.developer', 'nck3');
		User testUserNSCAfterSalesManager2 = TestDataSetFactory.createSampleUserUniqueUserName('un4@mytestdomain.developer', 'nck4');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactGTA2 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact2',
		                                      FirstName = 'firstname2',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 71',
		                                      MailingPostalCode = '80331',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactManager1 = new Contact(
		                                          AccountId = testAccount.Id,
		                                          LastName = 'TestContact3',
		                                          FirstName = 'firstname3',
		                                          MailingCountry = 'Germany',
		                                          MailingStreet = 'Sonnenstraße 60',
		                                          MailingPostalCode = '80334',
		                                          MailingCity = 'Stuttgart',
		                                          Job_Title__c = 'Employee',
		                                          Customer_type__c = 'Contact person only'
		);

		Contact testContactManager2 = new Contact(
		                                          AccountId = testAccount.Id,
		                                          LastName = 'TestContact4',
		                                          FirstName = 'firstname3',
		                                          MailingCountry = 'Germany',
		                                          MailingStreet = 'Sonnenstraße 58',
		                                          MailingPostalCode = '80334',
		                                          MailingCity = 'Stuttgart',
		                                          Job_Title__c = 'Employee',
		                                          Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c gtaEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA2.Id, testUserGTA2.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c managerEmployee = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactManager1.Id, testUserNSCAfterSalesManager.Id, 'NSC Aftersales Manager', gtaEmployeeRecordTypeId);
		Employee__c managerEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactManager2.Id, testUserNSCAfterSalesManager2.Id, 'NSC Aftersales Manager', gtaEmployeeRecordTypeId);

		serviceCenterDepartment.NSC_Aftersales_Manager__c = managerEmployee.Id;
		update serviceCenterDepartment;

		managerEmployee.EmploymentStatus__c = 'On Leave';
		managerEmployee.Representative__c = managerEmployee2.Id;
		update managerEmployee;



		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		GTA__c gta2 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee2.Id
		);
		gtaLIst.add(gta2);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(null, acc1.Assigned_GTA__c, 'Assigned GTA');

	}

	@isTest
	private static void createAccount2GTA1Inactive() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		User testUserGTA2 = TestDataSetFactory.createSampleUserUniqueUserName('un2@mytestdomain.developer', 'nck2');
		//User testUserNSCAfterSalesManager = TestDataSetFactory.createSampleUserUniqueUserName('un3@mytestdomain.developer', 'nck3');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactGTA2 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact2',
		                                      FirstName = 'firstname2',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 71',
		                                      MailingPostalCode = '80331',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactManager1 = new Contact(
		                                          AccountId = testAccount.Id,
		                                          LastName = 'TestContact3',
		                                          FirstName = 'firstname3',
		                                          MailingCountry = 'Germany',
		                                          MailingStreet = 'Sonnenstraße 60',
		                                          MailingPostalCode = '80334',
		                                          MailingCity = 'Stuttgart',
		                                          Job_Title__c = 'Employee',
		                                          Customer_type__c = 'Contact person only'
		);
		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c gtaEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA2.Id, testUserGTA2.Id, 'GTA', gtaEmployeeRecordTypeId);
		//Employee__c managerEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactManager1.Id, testUserNSCAfterSalesManager.Id, 'NSC Aftersales Manager', gtaEmployeeRecordTypeId);

		gtaEmployee2.EmploymentStatus__c = 'Inactive';
		update gtaEmployee2;

		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		GTA__c gta2 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee2.Id
		);
		gtaLIst.add(gta2);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee1.Id, acc1.Assigned_GTA__c, 'Assigned GTA');
	}

	@isTest
	private static void createAccount2GTAInactiveTheAssigned() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');
		User testUserGTA2 = TestDataSetFactory.createSampleUserUniqueUserName('un2@mytestdomain.developer', 'nck2');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);
		Contact testContactGTA2 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact2',
		                                      FirstName = 'firstname2',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 71',
		                                      MailingPostalCode = '80331',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);
		Employee__c gtaEmployee2 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA2.Id, testUserGTA2.Id, 'GTA', gtaEmployeeRecordTypeId);

		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee1.Id, acc1.Assigned_GTA__c, 'Assigned GTA');

		//Assign a new GTA to department
		GTA__c gta2 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee2.Id
		);
		insert gta2;
		//Inactivate the Assigned GTA
		gtaEmployee1.EmploymentStatus__c = 'Inactive';
		update gtaEmployee1;

		Test.stopTest();

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee2.Id, acc1.Assigned_GTA__c, 'Assigned GTA');
	}

	@isTest
	private static void createAccount2GTAInactiveTheAssignedNoOtherActive() {
		Test.setMock(HttpCalloutMock.class, new CalloutMocksTest.GlobalHttpCalloutMock());
		//User
		User testUserGTA1 = TestDataSetFactory.createSampleUserUniqueUserName('un1@mytestdomain.developer', 'nck1');

		//Department
		Department__c retailstoreDepartment = TestDataSetFactory.createDepartment('DEP123', 'retailstoreDepartment');
		Department__c serviceCenterDepartment = TestDataSetFactory.createDepartment('SC123', 'serviceCenterDepartment');
		serviceCenterDepartment.RecordTypeId = Schema.SObjectType.Department__c.getRecordTypeInfosByDeveloperName().get('Service_Center').getRecordTypeId();
		serviceCenterDepartment.Country__c = 'Germany';
		serviceCenterDepartment.City__c = 'München';
		serviceCenterDepartment.Zipcode__c = '80638 ';
		serviceCenterDepartment.Street__c = 'Wintrichring 1';
		serviceCenterDepartment.Geolocation__Latitude__s = 48.164045;
		serviceCenterDepartment.Geolocation__Longitude__s = 11.507327;
		update serviceCenterDepartment;

		//Account
		Account testAccount = TestDataSetFactory.createSampleAccount(retailstoreDepartment.id);


		//Contact
		Contact testContactGTA1 = new Contact(
		                                      AccountId = testAccount.Id,
		                                      LastName = 'TestContact1',
		                                      FirstName = 'firstname1',
		                                      MailingCountry = 'Germany',
		                                      MailingStreet = 'Sonnenstraße 61',
		                                      MailingPostalCode = '80332',
		                                      MailingCity = 'Stuttgart',
		                                      Job_Title__c = 'Employee',
		                                      Customer_type__c = 'Contact person only'
		);

		//Employee
		Id gtaEmployeeRecordTypeId = Schema.SObjectType.Employee__c.getRecordTypeInfosByDeveloperName().get('GTA_Employee').getRecordTypeId();

		Employee__c gtaEmployee1 = TestDataSetFactory.createEmployeeWithSpecificRole(serviceCenterDepartment.Id, testContactGTA1.Id, testUserGTA1.Id, 'GTA', gtaEmployeeRecordTypeId);

		//GTA__c
		List<GTA__c> gtaLIst = new List<GTA__c> ();
		GTA__c gta1 = new GTA__c(
		                         Department__c = serviceCenterDepartment.Id,
		                         Employee__c = gtaEmployee1.Id
		);
		gtaLIst.add(gta1);
		insert gtaLIst;

		//--!! testcase !!--
		Test.startTest();
		Account acc1 = new Account(
		                           BillingCountry = 'Germany',
		                           BillingStreet = 'Niddastraße 49',
		                           BillingPostalCode = '60329',
		                           BillingCity = 'Frankfurt am Main',
		                           PersonMailingCountry = 'Germany',
		                           PersonMailingStreet = 'Niddastraße 49',
		                           PersonMailingPostalCode = '60329',
		                           PersonMailingCity = 'Frankfurt am Main',
		                           PersonMailingLatitude = 50.10989,
		                           PersonMailingLongitude = 8.66481,
		                           FirstName = 'Test',
		                           LastName = 'PersonAccount',
		                           Salutation = 'Ms.',
		                           Major_Language__c = 'en_US',
		                           Preferred_ZipCode__c = '12345',
		                           Contact_Details__c = 'Email',
		                           Customer_type__pc = 'Prospect',
		                           RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId(),
		                           PreferredFacility__pc = retailstoreDepartment.Id,
		                           SMSConsent__pc = true,
		                           TelephoneConsent__pc = true,
		                           EmailConsent__pc = true
		);
		insert acc1;

		acc1.Customer_type__pc = 'Owner';
		update acc1;

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee1.Id, acc1.Assigned_GTA__c, 'Assigned GTA');

		//Inactivate the Assigned GTA
		gtaEmployee1.EmploymentStatus__c = 'Inactive';
		update gtaEmployee1;

		acc1 = [SELECT Id, Department__c, Assigned_GTA__c, BillingLatitude, BillingLongitude FROM Account WHERE Id = :acc1.Id];
		System.assertEquals(serviceCenterDepartment.Id, acc1.Department__c, 'Service Center');
		System.assertEquals(gtaEmployee1.Id, acc1.Assigned_GTA__c, 'Assigned GTA');

	}
}