force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Public_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Department_Public_Group_Id__c</fullName>
    <label>Department Public Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Created By: Reza Sarwari, User Story: https://jira.hyundai-autoever.eu/browse/GD-1285</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/GME_EmployeeTriggerHandlerTest.cls
@isTest
public class GME_EmployeeTriggerHandlerTest {
    
    @isTest
    public static void addToPublicGroupTest(){
        Account acc = AfterSales_TestFactory.getAccount('AtestAcc', true);
        Contact con = AfterSales_TestFactory.getContact(acc.Id, 'fName', 'lName', true);
        Department__c dep = AfterSales_TestFactory.getDepartmentStore('Store','StoreCode', true);

        Group g = new Group(Name = 'Test group');
        insert g;
        dep.Department_Public_Group_Id__c = g.Id;
        update dep;

        Test.startTest();
            Employee__c emp = AfterSales_TestFactory.getEmployee('testEmp', dep.Id, UserInfo.getUserId(), con.Id, true);
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM GroupMember WHERE GroupId =: g.Id].size());
    }
}