force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 10th Nov 2020
Purpose: This field will store the dealer code for the department</description>
    <label>Department Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Part_Item__c.field-meta.xml
<CustomField>
    <fullName>Part_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 09/11/2020
User Story: Gd-1222
Purpose :- After Sales service available of Customer.</description>
    <label>Part Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Department</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/SalesCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCompanyCode__c</fullName>
    <description>Sales Company Code</description>
    <label>Sales Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCompanyCode__c</fullName>
    <label>Sales Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ExternalIdCXP__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdCXP__c</fullName>
    <description>ODS_CRP + ODS_DLR_CD + ODS_DLR_ORD_NO</description>
    <externalId>true</externalId>
    <label>External Id (CXP)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/OrderNoCXP__c.field-meta.xml
<CustomField>
    <fullName>OrderNoCXP__c</fullName>
    <description>생성규칙 (Order일자) + 주문헤더 갯수 (현재 최고값 + 1) (법인코드 + 딜러코드별)
  - YYYY(4)+MM(2)+DD(2)+SEQ(2)</description>
    <label>Order No (CXP)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ShipMode__c.field-meta.xml
<CustomField>
    <fullName>ShipMode__c</fullName>
    <label>Ship Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>G</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/ExternalIdCXP__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdCXP__c</fullName>
    <externalId>true</externalId>
    <label>External Id (CXP)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/OrderedPartNo__c.field-meta.xml
<CustomField>
    <fullName>OrderedPartNo__c</fullName>
    <label>Ordered Part No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequestLineItem/fields/OrderLineNoCXP__c.field-meta.xml
<CustomField>
    <fullName>OrderLineNoCXP__c</fullName>
    <label>Order Line No (CXP)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AS_SubmitPO_AmosRestAPITest.cls
/******************************************************************************************
  * File Name   : AS_SubmitPO_AmosRestAPITest
  * Created Date: 16th December 2020
  * Description : Test class for AS_SubmitPO_AmosRestAPI.cls. API is required for GD-1391 ( Integration: submit purchase order ) and GD-1393 ( Integration: shipping information for purchase order ). It allows to send and recieive REST calls to/from AMOS system.
  * Author      : Konrad Maluszkiewicz
  * Modification Log
  * =======================================================================
  * Ver     Date             Author                      Modification
  * =======================================================================
  * 1.0     16.12.2020       Konrad Maluszkiewicz        Creation
  ****************************************************************************************/

@isTest
private class AS_SubmitPO_AmosRestAPITest {
    @testSetup
    static void setupTestData() {
        Product2 prod2 = new Product2();
        prod2.Name = 'Local test product2';
        prod2.CurrencyIsoCode = 'EUR';
        prod2.IsActive = true;
        insert prod2;

        Department__c department = new Department__c();
        department.Department_Code__c = 'test_department_code';
        department.SalesCompanyCode__c = 'test';
        department.Part_Item__c = prod2.Id;
        insert department;

        ProductRequest prodReq = new ProductRequest();
        prodReq.OrderNoCXP__c = 'CXPOrderNo';
        prodReq.OrderType__c = 'S';
        prodReq.ShipMode__c = 'E';
        prodReq.Description = 'test description';
        prodReq.Department__c = department.Id;
        prodReq.ExternalIdCXP__c = 'EXT_ID_1_TEST';
        prodReq.Status = 'Draft';
        prodReq.ShipmentType = 'Rush';
        insert prodReq;

        // List<ProductRequestLineItem> productRequestLineItemsList = new List<ProductRequestLineItem>();
        // ProductRequestLineItem prodReqLineItem;

        // for(Integer i=0;i<3;i++) {
        //     prodReqLineItem = new ProductRequestLineItem();
        //     prodReqLineItem.ParentId = prodReq.Id;
        //     prodReqLineItem.OrderLineNoCXP__c = 'oln' + i;
        //     prodReqLineItem.OrderedPartNo__c = 'opn' + i;
        //     prodReqLineItem.QuantityUnitOfMeasure = 'Each';
        //     prodReqLineItem.Product2Id = prod2.Id;

        //     productRequestLineItemsList.add(prodReqLineItem);
        // }

        // insert productRequestLineItemsList;
    }

    // @isTest static void testMethod1() {
    //     List<ProductRequest> prodRequestsList = [SELECT Id FROM ProductRequest];
    //     System.assertEquals(1, prodRequestsList.size());

    //     List<Department__c> departmentsList = [SELECT Id FROM Department__c];
    //     System.assertEquals(1, departmentsList.size());

    //     List<Product2> products2List = [SELECT Id FROM Product2];
    //     System.assertEquals(1, products2List.size());

    //     List<ProductRequestLineItem> productRequestLineItemsList = [SELECT Id FROM ProductRequestLineItem];
    //     System.assertEquals(3, productRequestLineItemsList.size());
    // }

    @isTest
    static void testSendProdReqToAMOS() {
        AS_SubmitPO_AmosHttpCalloutMock amosProdReqHttpCalloutMock = new AS_SubmitPO_AmosHttpCalloutMock();
        Test.setMock(HttpCalloutMock.class, amosProdReqHttpCalloutMock);

        Test.startTest();
        Id prodReqId = [SELECT Id FROM ProductRequest WHERE ExternalIdCXP__c = 'EXT_ID_1_TEST'].Id;
        System.debug('prodReqId = ' + prodReqId);
        HttpResponse httpResp = AS_SubmitPO_AmosRestAPI.sendProdReqToAMOS(prodReqId);
        System.assertEquals(200, httpResp.getStatusCode(), 'Error: status code of response for sendProdReqToAMOS callout should be equal to: 200');
        Test.stopTest();
    }

    @isTest
    static void testUpsertProductRequest() {
        ProductRequest prodReq = [SELECT ShipMode__c FROM ProductRequest WHERE ExternalIdCXP__c = 'EXT_ID_1_TEST'];
        System.assertEquals('E',prodReq.ShipMode__c,'Error: ProductRequest.ShipMode__c field before inbound REST call should have value of: \'E\'');
        RestRequest request = new RestRequest();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/ProductRequestAPI';
        request.httpMethod = 'PUT';
        request.requestBody = Blob.valueOf('{"ExternalIdCXP__c" : "EXT_ID_1_TEST","ShipMode__c" : "G","Status" : "Received","ShipmentType" : "Pick Up"}');
        RestContext.request = request;
        AS_SubmitPO_AmosRestAPI.upsertProductRequest();

        prodReq = [SELECT ShipMode__c FROM ProductRequest WHERE ExternalIdCXP__c = 'EXT_ID_1_TEST'];
        System.debug('after inbound REST call # prodReq = ' + prodReq);
        System.assertEquals('G',prodReq.ShipMode__c,'Error: ProductRequest.ShipMode__c field after inbound REST call should have value of: \'G\'');
    }

// @isTest static  void testGetCallout() {
//     // Create the mock response based on a static resource
//     StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
//     mock.setStaticResource('GetAnimalResource');
//     mock.setStatusCode(200);
//     mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
//     // Associate the callout with a mock response
//     Test.setMock(HttpCalloutMock.class, mock);
//     // Call method to test
//     HttpResponse result = AnimalsCallouts.makeGetCallout();
//     // Verify mock response is not null
//     System.assertNotEquals(null,result,
//         'The callout returned a null response.');
//     // Verify status code
//     System.assertEquals(200,result.getStatusCode(),
//         'The status code is not 200.');
//     // Verify content type   
//     System.assertEquals('application/json;charset=UTF-8',
//         result.getHeader('Content-Type'),
//         'The content type value is not expected.');  
//     // Verify the array contains 3 items     
//     Map<String, Object> results = (Map<String, Object>) 
//         JSON.deserializeUntyped(result.getBody());
//     List<Object> animals = (List<Object>) results.get('animals');
//     System.assertEquals(3, animals.size(),
//         'The array should only contain 3 items.');          
// }
}