force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Confirmed By Hamid</description>
    <label>Representative</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <inlineHelpText>Thies field value will be copied into the Account Team Member Role.
The Employee within the role &quot;Store Manager&quot; becomes Account Owner for all Accounts where his department is the PreferredFacility.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Adviser</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Warranty Manager</fullName>
            </value>
            <value>
                <fullName>Insurance Manager</fullName>
            </value>
            <value>
                <fullName>Store Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Test Drive Manager</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Inventory Manager</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Receptionist</fullName>
            </value>
            <value>
                <fullName>Pick-up driver</fullName>
            </value>
            <value>
                <fullName>Parts Manager</fullName>
            </value>
            <value>
                <fullName>GTA</fullName>
            </value>
            <value>
                <fullName>NSC Aftersales Manager</fullName>
            </value>
            <value>
                <fullName>Department Manager</fullName>
            </value>
            <value>
                <fullName>Butler</fullName>
                <isActive>false</isActive>
                <label>Butler</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GTA__c/GTA__c.object-meta.xml
<CustomObject>
    <description>GD-2173, GD-2170</description>
    <label>GTA</label>
    <nameField>
        <displayFormat>GTA-{000000}</displayFormat>
        <label>GTA&apos;s Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GTAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GTA__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GTA__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The employee&apos;s role should be GTA.</errorMessage>
        <filterItems>
            <field>Employee__c.Role__c</field>
            <operation>equals</operation>
            <value>GTA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>GTAs</relationshipLabel>
    <relationshipName>GTAs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GTA__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created to identify the Primary GTA in the department. One department can have multiple GTA&apos;s but it should only have one primary GTA.</description>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AfterSales_SendCustNotiHandler_GTAofDep.cls
/**
 * @author Daniel Varhidi
 * @description 
 * @created 21/01/2021
*/
public class AfterSales_SendCustNotiHandler_GTAofDep {

	/**
	 * @description 
	 * @param request 
	 */
	@InvocableMethod(label = 'Send Custom Notification to GTA of Department' description = 'Send Custom Notification' category = 'Custom Notification')
	public static void sendNotificationFromProcessBuilderToGTAofDepartment(List<FlowInputs> request) {

		for (FlowInputs input : request) {
			GTA__c gta = AfterSales_SendCustNotiHandler_GTAofDep.getGTAEmployeeFromDepartmentId(input.servicecenterIdString);
			if (gta != null) {
				List<AfterSales_SendCustomNotification.FlowInputsSampleNotification> sampleNotiInputList = new List<AfterSales_SendCustomNotification.FlowInputsSampleNotification> ();
				AfterSales_SendCustomNotification.FlowInputsSampleNotification sampleNotiInput = new AfterSales_SendCustomNotification.FlowInputsSampleNotification();
				sampleNotiInput.titleEnglish = input.titleEnglish;
				sampleNotiInput.bodyEnglis = input.bodyEnglis;
				sampleNotiInput.titleGerman = input.titleGerman;
				sampleNotiInput.bodyGerman = input.bodyGerman;
				sampleNotiInput.notificationTypeDeveloperName = input.notificationTypeDeveloperName;
				sampleNotiInput.targetIdString = input.targetIdString;
				sampleNotiInput.employeeIdString = String.valueOf(AfterSales_SendCustomNotification.getEmployeeById(gta.Employee__r.Id).Id);
				sampleNotiInputList.add(sampleNotiInput);
				AfterSales_SendCustomNotification.sendSampleNotificationFromProcessBuilder(sampleNotiInputList);
			}
		}

	}

	/**
	 * @description input details that comes to apex from flow
	 */
	public class FlowInputs {

		@InvocableVariable
		public String titleEnglish;

		@InvocableVariable
		public String bodyEnglis;

		@InvocableVariable
		public String titleGerman;

		@InvocableVariable
		public String bodyGerman;

		@InvocableVariable
		public String notificationTypeDeveloperName;

		@InvocableVariable
		public String targetIdString;

		@InvocableVariable
		public String servicecenterIdString;

	}

	/**
	 * @description 
	 * @param servicecenterIdString 
	 * @return 
	 */
	public static GTA__c getGTAEmployeeFromDepartmentId(String servicecenterIdString) {
		List<GTA__c> gtaList = [
		                        SELECT Id, Employee__r.Id
		                        FROM GTA__c
		                        WHERE Department__c = :servicecenterIdString
		                        AND Employee__r.Role__c != 'Inactive'
                				AND IsPrimary__c = True
		                        LIMIT 1
		                       ];
		if (!gtaList.isEmpty()) {
			return gtaList.get(0);
		}
		return null;
	}
}