force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>사원정보, 시스템사용자(User)정보와 별도의 사원 인사정보
Created By : Riddhi Mittal
Created Date: 10/21/2020
User Story:GD-715
Purpose: Basic level object</description>
    <label>Employee</label>
    <nameField>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Riddhi Mittal
Created Date: 10/22/2020
User Story: GD-715
Purpose: Basic Field of Employee</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AfterSales_Recommendation__c.field-meta.xml
<CustomField>
    <fullName>AfterSales_Recommendation__c</fullName>
    <description>This Field created for Recommendation</description>
    <label>Recommendation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AfterSales_Supersession__c.field-meta.xml
<CustomField>
    <fullName>AfterSales_Supersession__c</fullName>
    <description>This field created for Suppression 
Created By: Shashikant Bagale</description>
    <label>Supersession</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DAOSMinimumOrderQuantity__c.field-meta.xml
<CustomField>
    <fullName>DAOSMinimumOrderQuantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Created By: Mayank Pant Created Date: 21st Oct 2020 User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 Purpose:</description>
    <label>DAOS Minimum Order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Created By: Mayank Pant Created Date: 21st Oct 2020 User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 Purpose:</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Created By: Manoj Kumar
Created Date: 29/10/2020
User Story: GD-1297
Purpose :- After Sales record of Customer.</description>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Model</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <description>US- 2148, Created by- Riddhi Mittal on 1/14/2021</description>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductNameNative__c.field-meta.xml
<CustomField>
    <fullName>ProductNameNative__c</fullName>
    <description>Created By: Mayank Pant Created Date: 21st Oct 2020 User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 Purpose:</description>
    <label>Product Name (Native)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Created By: Mayank Pant
Created Date: 27th Oct 2020
User Story:
Purpose:</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Created By: Mayank Pant Created Date: 21st Oct 2020 User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 Purpose:</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <label>Part</label>
       
</RecordType>

force-app/main/default/objects/ProductItem/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By : Nagendra Lagisetty
Created Date: 11/4/2020
User Story:GD-822
Purpose: Basic level object</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Product Items</relationshipLabel>
    <relationshipName>Product_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Model.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>G70</fullName>
    </customValue>
    <customValue>
        <fullName>G80</fullName>
    </customValue>
    <customValue>
        <fullName>G90</fullName>
    </customValue>
    <customValue>
        <fullName>GV80</fullName>
    </customValue>
    <description>Created By: Manoj Kumar
Created Date: 29/10/2020
User Story: GD-
Purpose :- After Sales record of Customer.</description>
    <masterLabel>Model</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AfterSales_ProductNewRequestLineItem.cls
/**
Author: Shashikant Bagale
Company: CTS
Date:  31/12/2020 
Description: Get Product request Line Item.
*/
public without sharing class AfterSales_ProductNewRequestLineItem {
    
    
    @AuraEnabled
    /*  public static List <PriceBookEntry> getRequestProductNewItem(String searchKeyWord){ 
List <PriceBookEntry> returnListProductLineItem = new List <PriceBookEntry> (); 
String searchString = '%' + searchKeyWord + '%';        
List <PriceBookEntry> lstOfProductLineItem =[
SELECT Product2.Id,Product2.recordtype.name ,Product2.Name, Product2.ProductCode,Product2.Description, Product2.ProductNameNative__c,Product2.Family,Product2.StartDate__c,Product2.Quantity__c,Product2.DAOSMinimumOrderQuantity__c,Product2.EndDate__c,Product2.Model__c,PricebookEntry.UnitPrice,Product2.AfterSales_Recommendation__c,Product2.AfterSales_Supersession__c from PriceBookEntry where ((Product2.productcode like :searchString) or (Product2.name like :searchString)) and Product2.recordtype.name='Part' ];
return lstOfProductLineItem;
}
select id,QuantityOnHand,Product2.productcode,Product2.Id,Product2.recordtype.name ,Product2.Name,
Product2.Description,Product2.ProductNameNative__c,Product2.Family,Product2.Price_Per_Unit__c,
Product2.StartDate__c,Product2.Quantity__c,Product2.DAOSMinimumOrderQuantity__c,Product2.EndDate__c,
Product2.Model__c,Product2.AfterSales_Recommendation__c,Product2.AfterSales_Supersession__c 
from ProductItem */
    
    public static List <Product2> getRequestProductNewItem(String searchKeyWord){         
        List <Product2> returnListProductLineItem = new List <Product2> (); 
        List<Employee__c>  lstDepartment =new List<Employee__c>();
        lstDepartment  = [SELECT id, department__c,User__c FROM Employee__c where User__c=: userInfo.getUserId()] ;   
        String searchString = '%' + searchKeyWord + '%';   
        List <Product2> lstOfProductLineItem =[  
            SELECT Id,productcode,recordtype.name,Name,Description,ProductNameNative__c,Family,Price_Per_Unit__c,StartDate__c,Quantity__c,
            DAOSMinimumOrderQuantity__c,EndDate__c,Model__c,AfterSales_Recommendation__c,AfterSales_Supersession__c,
            (SELECT Id,QuantityOnHand FROM ProductItems  ORDER BY LastModifiedDate DESC LIMIT 1  ) 
            FROM Product2 
            WHERE ((productcode like :searchString) or (name like :searchString))            
            AND recordtype.name='Part' ];
        return lstOfProductLineItem;
        //where Department__c=:lstDepartment[0].Department__c
    }
    
    @AuraEnabled
    public static String getRequestProductNumber(String recordId){  	
        List<ProductRequest> lstProductRequest =[SELECT ProductRequestNumber FROM ProductRequest where Id=:recordId]; 
        return lstProductRequest[0].ProductRequestNumber;
    }  
    
    @AuraEnabled
    public static ProductRequestLineItem saveProductRequestLineItem(ProductRequestLineItem objProductRequestLineItem) {
        upsert objProductRequestLineItem;
        return objProductRequestLineItem;
    }
    
    @AuraEnabled
    public static string getSupersessionProductNewItem(String searchSupersessionKeyWord){ 
        
        String searchSupersessionString = '%' + searchSupersessionKeyWord + '%';        
        List <Product2> lstSupersessionProductLineItem =[ SELECT Id, Name from Product2  where  Name like :searchSupersessionString];        
        return lstSupersessionProductLineItem[0].Id;
    } 
    
}