force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Organization information, Sales/Service Center, Exhibition hall / test drive center / delivery center, etc.

Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Created By: Reza Sarwari, User Story: https://jira.hyundai-autoever.eu/browse/GD-1285</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Location/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: Manoj Kumar
Created Date: 10/11/2020
User Story: Gd-964
Purpose :- After Sales service available of Customer.</description>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductNameNative__c.field-meta.xml
<CustomField>
    <fullName>ProductNameNative__c</fullName>
    <description>Created By: Mayank Pant Created Date: 21st Oct 2020 User Story: https://jira.hyundai-autoever.eu/browse/GD-1238 Purpose:</description>
    <label>Product Name (Native)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>W</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductRequest/fields/ShipMode__c.field-meta.xml
<CustomField>
    <fullName>ShipMode__c</fullName>
    <label>Ship Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>G</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AS_TestProductNewRequestLineItem.cls
/**
Author: Shashikant Bagale
Company: CTS
Date:  31/12/2020 
Description: Test class for batch class to update/Create Pricbookentry
*/

@isTest
public class AS_TestProductNewRequestLineItem {
    // This is used for the new request product new Item.   
    static testMethod void testgetRequestProductNewItem() {   
        product2 ProductLineItem = new product2(name='Product1', productcode='PR-001',ProductNameNative__c='Native',Family='',Description='Demo Car');
        insert ProductLineItem;
        List <product2> returnListProductLineItem = new List <product2> ();       
        Test.startTest();
        returnListProductLineItem= AfterSales_ProductNewRequestLineItem.getRequestProductNewItem('strValue');        
        Test.stopTest();
    } 
    
    // This test method used for fetch Product Numbers
    static testMethod void testgetRequestProductNumber() { 
        Department__c dep = AfterSales_TestFactory.getDepartmentStore('Store','StoreCode', false);  
        insert dep;   
        ProductRequest objProductRequest = new ProductRequest(OrderType__c='S',ShipMode__c='G',Department__c=dep.id); 
        insert objProductRequest;    
        Test.startTest();
        string strProductRequestNumber= AfterSales_ProductNewRequestLineItem.getRequestProductNumber(objProductRequest.id);        
        Test.stopTest();
    }  
    
    // Product Request Line Item used for the Save the line Item.  
   static testMethod void test_saveProductRequestLineItem() { 
        Department__c dep = AfterSales_TestFactory.getDepartmentStore('Store','StoreCode', false);  
        insert dep;   
        Schema.Location loc=TestDataSetFactory.createLocation('Warehouse','loc',dep.Id,true);       
        product2 ProductLineItem = new product2(name='Product1', productcode='PR-001',ProductNameNative__c='Native',Family='',Description='Demo Car');
        insert ProductLineItem;        
        ProductRequest objProductRequest = new ProductRequest(OrderType__c='S',ShipMode__c='G',Department__c=dep.Id);
        insert objProductRequest;          
        ProductRequestLineItem objProductRequestLineItem = new ProductRequestLineItem(ParentId=objProductRequest.id,Product2Id=ProductLineItem.id,Description='Test Description',QuantityRequested=5);        
        insert objProductRequestLineItem;        
        Test.startTest();
        ProductRequestLineItem objProductRequestLineItemReturn= AfterSales_ProductNewRequestLineItem.saveProductRequestLineItem(objProductRequestLineItem);        
        Test.stopTest();
    }    
    static testMethod void testgetSupersessionProductNewItem() {            
        product2 ProductLineItem = new product2(name='Product1', productcode='PR-001',ProductNameNative__c='Native',Family='',Description='Demo Car');
        insert ProductLineItem;    
        Test.startTest();
        string strProductRequestNumber= AfterSales_ProductNewRequestLineItem.getSupersessionProductNewItem(ProductLineItem.Name);        
        Test.stopTest();
    }   
}